// Generated by pilot/scripts/substack_to_articles_ts.py
// Source: https://ethancho12.substack.com/feed
// Generated: 2026-04-14T08:35:55
// New articles: 1 (not yet present in articles.ts)
//
// HOW TO USE:
// 1. Review each object below — titles, slugs, categories, excerpts
// 2. For Korean posts, swap the [Korean] title prefix for a real
//    English title (so cards display well in the /insights grid)
// 3. Copy the entire array contents into the `articles: Article[]`
//    declaration in app/data/articles.ts (append to the end)
// 4. Run `npm run build` to verify no TS errors
// 5. Spot-check /insights and /insights/<slug> in dev
//

import { Article } from '@/app/data/articles';

export const newArticlesFromSubstack: Article[] = [
  {
    title: "[LP] Asia’s Last Non-Competitive Venture Market",
    excerpt: "The KOSPI rose more than 75% in 2025, its best year in over two decades and the strongest performance of any major global index.",
    date: "Apr 13, 2026",
    category: "Market Analysis",
    readTime: "7 min",
    substackUrl: "https://ethancho12.substack.com/p/lp-asias-last-non-competitive-venture",
    slug: "lp-asias-last-non-competitive-venture-market",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "competitive", "venture", "market"],
    wordCount: 1444,
    rating: 3,
    content: `[![](https://substackcdn.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc5e92442-dc9e-4fee-83f6-76b1e755dd59_1080x1468.jpeg)](https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc5e92442-dc9e-4fee-83f6-76b1e755dd59_1080x1468.jpeg)

The KOSPI rose more than 75% in 2025, its best year in over two decades and the strongest performance of any major global index.

Over the same twelve months, Korean private capital deal value collapsed from $24 billion to $16 billion. Venture fundraising fell from $9.3 billion to $1.1 billion.

That gap between public market euphoria and private market paralysis is the widest I have seen in fifteen years covering this market across Google Korea, Qualcomm Ventures, Samsung’s Strategy & Innovation Center, KB Investment, and now TheVentures.

It will not stay this wide.

LPs who wait for confirmation will pay the recovery price, not the reset price.

### **Competition is for losers. Korea is where competition left.**

The best venture returns in history came from markets where one or two investors had privileged access and everyone else was absent. Sequoia in 1970s semiconductors. Benchmark in 1990s internet. Founders Fund in 2000s enterprise. The pattern repeats. Outsized returns do not come from outbidding ten other smart funds for the same deal. They come from being one of the few investors paying attention when a market is structurally mispriced.

***Korea in 2026 is that market.***

The sharpest LPs push back with the same question: if Korean venture is such a great opportunity, why did zero VC funds above $250 million close in 2025? Why did sub-$50 million funds collapse from 297 in 2022 to just 32?

***The answer is the entire thesis.***

2025 fundraising reflects underwriting decisions made in 2023 and 2024, during peak NPS commitment freeze, the Homeplus fallout, and regulatory uncertainty around PE leverage limits. Fundraising is the lagging indicator. It tells you what domestic LPs believed 18 months ago, not what the market looks like now. What the market looks like now is a competition vacuum.

The emerging-manager layer that normally bids up seed and Series A deals is gone. The mid-size funds that normally consolidate Series B rounds are gone. Into that vacuum walked foreign capital and corporate venture, which together took 40% and 63% of deal value respectively. Arm led Rebellions at a $1.4 billion valuation. FuriosaAI turned down an $800 million offer from Meta. The bids that cleared in 2025 came from investors with proprietary conviction and strategic reasons to be there. Everyone else was absent.

This is the shape of a market bottom. Not the absence of quality. The absence of competition for it. Every other major Asian venture market is either crowded (Japan, India), politically constrained (China), or structurally shallow (Southeast Asia).

Korea is the only developed Asian market where a dedicated manager can still enter quality deals without five other funds at the table.

### **The structural tailwind LPs are underweighting**

While domestic sentiment was retreating, Korean policy was loading the next cycle.

December 2025: the government launched the KRW 150 trillion National Growth Fund to back semiconductors, AI, robotics, biotech, and future mobility through direct equity, fund of funds, infrastructure financing, and lending. The Ministry of SMEs and Startups launched the “Four Venture Powerhouses” strategy with 2030 targets of KRW 40 trillion in annual venture investment, 10,000 AI and deep-tech startups funded, and 50 unicorns and decacorns created. M&A guarantees expand from KRW 30 billion to KRW 200 billion by 2030. The Korea Fund of Funds is being extended beyond its 2035 sunset in ten-year increments. A dedicated KRW 333.3 billion early-stage vehicle is being established. A Startup Venture Campus opened in Silicon Valley in January 2026, with additional hubs planned in Singapore, Tokyo, London, and New York.

Corporate acquirers are also pre-committed. Samsung, SK, Hyundai, and LG have collectively pledged KRW 800 trillion, about $580 billion, to AI, semiconductors, energy transition, and advanced manufacturing over five years. January 2026 reforms abolished the mandatory CVC divestment rule and raised the corporate contribution cap for accelerator-led funds from 30% to 40%. Strategic buyers for the 2026-2028 vintage are policy-enabled and capital-committed.

Pair these two facts. Entry prices are the cleanest they have been in six years because competition left the market. Exit demand is the most structurally loaded I have seen in fifteen years because policy and corporate capital both converged on the same destination.

That configuration does not exist anywhere else in Asia today.

### **Founder Intelligence is the actual asset class**

The narrow bet worth making is not “Korean VC.”   
It is a specific founder profile.

Korea is a high-context society where founders grow up reading rooms, managing hierarchy, and surviving compressed social feedback. The best of them then train inside American-style execution cultures, usually at a US tech company, a US-educated startup, or a cross-border subsidiary. The combination produces a founder who can sell into Bentonville on Monday and run a factory floor in Gumi on Friday.

I call this Founder Intelligence.

The Korean Diaspora cohort, founders operating natively across Seoul, the Bay Area, New York, and Tokyo, is where the outsized returns sit. They are unreachable through a standard pan-Asia fund. They do not show up in Seoul-only networks either. The manager needs feet in both worlds and a career arc that proves it.

### **Why most LPs will still miss this**

I have watched this movie before. Every cycle, foreign LPs who want Korea exposure end up in one of three dead ends.

1. They buy into a large Seoul-based generalist fund and get diluted into domestic-focused deal flow.
2. They take a pan-Asia fund where Korea becomes a 10% sleeve with no sourcing edge.
3. They co-invest opportunistically and only see deals at the price everyone else already bid up.

Each path feels like Korea exposure. None of them capture the actual trade. Each path also puts the LP back into a competitive market rather than the non-competitive one Korea currently offers.

The Korean Diaspora thesis requires a manager who sources domestically in Korean, underwrites in English, and whose LP base, portfolio logic, and career arc all point outward from Seoul by design rather than by accommodation. That description fits a small handful of firms globally.

My track record across earlier roles includes leading early investments in Toss and Dunamu during my time at Qualcomm Ventures, now two of Korea’s most valuable private companies.

TheVentures was founded by the Viki co-founders after their sale to Rakuten, and the firm was built from day one around cross-border founders rather than around the domestic Korean market.

Cross-border is the origin, not the marketing.

### **What you do in the next 90 days or leave on the table**

Three actions.

1. Ask your pan-Asia managers what share of their 2025 Korea allocation went into sub-$500 million pre-money rounds. The honest answer is almost always near zero. That is the gap the emerging-manager collapse just opened and the gap foreign LPs are currently mispricing as absence of opportunity rather than absence of competition.
2. Screen Korea-dedicated managers on one question: show me a portfolio of founders who scaled into the US market within 24 months of seed. If the answer is theoretical, pass. If the answer is a list of names with revenue, that is the Founder Intelligence signal. Most will fail this test.
3. Move before the National Growth Fund closes its first vintage and the KVIC Fund of Funds extension is ratified. The public market already priced in Korea’s governance reforms and added 75% in twelve months. Private markets are 18 months behind the same signal. LPs who enter now are buying the reset. LPs who wait are buying the recovery, against ten other funds that finally noticed.

The capital is already flowing. Arm. Meta. KKR. Air Liquide. The question is not whether foreign capital is moving into Korea.

It is whether you are moving with it now, while the market is still empty, or after everyone else arrives.

---

*Ethan Cho (조여준) is Chief Investment Officer at TheVentures, a Seoul-based early-stage venture firm founded by the Viki co-founders. His 20-plus year career spans Google Korea, Qualcomm Ventures (where he led early investments in Toss and Dunamu), Samsung Strategy & Innovation Center, KB Investment, and Fast Ventures. BBA, Seoul National University. MBA, Columbia Business School. Ranked #1 Korean LinkedIn influencer (Favikon, 2026).*`,
  },

];
