// Generated by pilot/scripts/substack_to_articles_ts.py
// Source: https://ethancho12.substack.com/feed
// Generated: 2026-04-12T09:23:25
// New articles: 15 (not yet present in articles.ts)
//
// HOW TO USE:
// 1. Review each object below — titles, slugs, categories, excerpts
// 2. For Korean posts, swap the [Korean] title prefix for a real
//    English title (so cards display well in the /insights grid)
// 3. Copy the entire array contents into the `articles: Article[]`
//    declaration in app/data/articles.ts (append to the end)
// 4. Run `npm run build` to verify no TS errors
// 5. Spot-check /insights and /insights/<slug> in dev
//

import { Article } from '@/app/data/articles';

export const newArticlesFromSubstack: Article[] = [
  {
    title: "Korea’s $13 Billion Venture Market Has a Body Composition Problem",
    excerpt: "Last quarter, Korean venture investment hit ₩2.18 trillion ($1.6B) — up 34% year-over-year. AI captured 45% of all deployment. The government committed to its largest-ever capital injection cycle: ₩3,500 billion in…",
    date: "Apr 10, 2026",
    category: "Korea VC",
    readTime: "6 min",
    canonicalUrl: "https://ethancho12.substack.com/p/koreas-13-billion-venture-market",
    slug: "koreas-13-billion-venture-market-has-a-body-composition-prob",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "venture", "market", "billion", "composition", "korea", "problem"],
    wordCount: 1242,
    rating: 3,
    content: `Last quarter, Korean venture investment hit ₩2.18 trillion ($1.6B) — up 34% year-over-year. AI captured 45% of all deployment. The government committed to its largest-ever capital injection cycle: ₩3,500 billion in fresh fund-of-funds allocation, a ₩7.45 trillion growth fund, ₩400 billion from the national pension, and a new retail venture investment channel (BDC) that went live in March.

[![South Korea Launches 'Startup Korea Fund' to Boost Private Investment in  Innovation - Businesskorea](https://substackcdn.com/image/fetch/$s_!nXw5!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa3d99ebf-e70e-4443-86bd-222315950a2c_302x167.jpeg "South Korea Launches 'Startup Korea Fund' to Boost Private Investment in  Innovation - Businesskorea")](https://substackcdn.com/image/fetch/$s_!nXw5!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa3d99ebf-e70e-4443-86bd-222315950a2c_302x167.jpeg)

The headlines say: Korea’s venture ecosystem is thriving.

The body composition says something else.

## The DEXA Scan

A DEXA scan measures what a mirror can’t. Not weight, but what the weight is made of. Muscle versus fat. The Korean venture market needs one.

Here’s Q1 2026:

[![](https://substackcdn.com/image/fetch/$s_!hact!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa01c6935-a8ce-4a08-86c9-b0a6d992ef03_734x178.png)](https://substackcdn.com/image/fetch/$s_!hact!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa01c6935-a8ce-4a08-86c9-b0a6d992ef03_734x178.png)

More capital. Fewer companies. Larger checks into later rounds. The venture market is gaining weight while losing muscle.

## How Government Capital Becomes GLP-1

GLP-1 drugs — Ozempic, Wegovy, the newly FDA-approved oral Foundayo — are the most successful weight-loss intervention in pharmaceutical history. They work. Patients lose 15-25% of body weight. The mirror looks great.

The problem: 30-40% of the weight lost is lean muscle. And a meta-analysis of 8,000 patients showed that when the drug stops, the weight comes back — but it comes back as fat, not muscle. The patient ends up with worse body composition than before they started.

Korea’s government venture capital operates on the same mechanism.

The Korea Fund of Funds (모태펀드) is the dominant LP in Korean venture — directly or indirectly backing the majority of domestic VC funds. When the government injects capital, total investment rises (looks healthier on the scale). But the intervention simultaneously crowds out private LPs, distorts GP incentives toward government allocation criteria rather than market returns, and creates structural fund-life constraints (8-10 year mandates) that make true seed investing economically irrational.

The National Assembly Budget Office’s own data confirms it: the fund-of-funds’ leverage effect on private capital mobilization has been **declining since 2014**. Same dose, less effect. Classic drug tolerance.

The government’s response? Triple the dose. In the last 24 months: a new BDC retail channel, a 63% increase in fund-of-funds allocation, and a ₩7.45 trillion parallel growth fund. Three simultaneous interventions into an ecosystem already showing tolerance.

## What This Means for Allocators

If you’re a global LP evaluating Korea, the standard pitch is: “$13.6 billion market, government support, AI momentum, underpriced relative to the US.”

That pitch is technically accurate and structurally misleading. Here’s what to actually look for:

**1. The GP bifurcation is permanent.**

Large GPs now route through the National Growth Fund. Mid-tier GPs compete for the fund-of-funds. This creates two distinct species of Korean VC — and neither is optimized for what global LPs actually want (high-conviction early-stage with genuine alpha).

The GPs worth backing are the ones who *don’t* depend on government allocation. Ask any Korean GP: “What percentage of your LP base is government-linked?” If the answer is above 70%, you’re investing in a policy instrument, not a venture fund.

**2. The AI concentration is a feature and a bug.**

45% of Q1 deployment into AI sounds like conviction. Look closer: one semiconductor deal was 30% of the quarter. Strip out the top 3 deals and Korean AI venture drops to a modest allocation. The “AI boom” in Korean VC is actually 5-7 large checks, not a broad ecosystem shift.

The opportunity is *below* this layer — Korean AI startups at seed and pre-Series A that are invisible to government-funded GPs because the fund economics don’t support $200-500K checks with 10+ year horizons.

**3. The exit infrastructure is the real bottleneck.**

Korea has no meaningful tech M&A culture. Large corporates build rather than buy. The IPO pipeline is tightening with profitability requirements. There is no developed secondary market.

All the capital entering the system in H2 2026 creates portfolio companies that need to exit by 2033-2034. Into what? This is the question no government allocation announcement addresses. If you’re evaluating a Korean GP, their exit thesis matters more than their entry thesis.

**4. The emerging manager window is now.**

Precisely because the government-funded ecosystem is structurally oriented toward larger, later-stage, policy-aligned deployment — there is a genuine gap at the seed layer. The GPs filling this gap tend to be:

* Smaller (sub-$30M funds)
* Independently funded (non-government LP base)
* Sector-specialized (particularly in AI infrastructure and developer tools)
* Operationally involved (not check-writing, but company-building)

These managers are hard to find through traditional Korean VC channels because they don’t show up at government allocation presentations. They show up in founder communities, open-source ecosystems, and cross-border networks.

## The Framework: Execution, Decision, Responsibility

One lens we use to evaluate this market: when AI commoditizes Execution (code, analysis, operations), the value of venture capital migrates to two layers that cannot be automated — **Decision** (what to fund, when, at what terms) and **Responsibility** (fiduciary duty, board governance, LP accountability).

McKinsey’s 2026 AI Trust Survey, covering 500 organizations, arrived at the same conclusion independently: *“Agency isn’t a feature — it’s a transfer of decision rights.”*

[![](https://substackcdn.com/image/fetch/$s_!pEKM!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F57b1b3cd-b8ed-42f7-979b-a335e764be9b_856x1055.png)](https://substackcdn.com/image/fetch/$s_!pEKM!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F57b1b3cd-b8ed-42f7-979b-a335e764be9b_856x1055.png)

In a market flooded with government capital where Execution is cheap and abundant, the scarce resource is judgment. The GPs worth backing are the ones whose decision-making process — not their fund size or government connections — is the source of alpha.

## The Takeaway

Korea’s venture market is not broken. It’s structurally medicated. The patient looks healthy on the scale. The DEXA scan tells a different story.

For LPs considering Korea exposure: look past the headline numbers. Ask about body composition — early-stage pipeline, private LP co-investment ratios, exit infrastructure, GP independence from government allocation. The opportunity is real, but it lives in the muscle, not the weight.

---

*This is a part of an occasional series on Korean venture market structure for international allocators. If your allocation committee is evaluating Korea, I’m happy to share the underlying data.*

*Ethan Cho is based in Seoul and writes about venture capital, AI, and cross-border market structure. Previously at Google, Samsung, and Qualcomm.*`,
  },

  {
    title: "[For non-Korean LPs] Why Korea Is the Most Mispriced Startup Market in Asia",
    excerpt: "Consider a counterfactual. K-pop Demon Hunters becomes a global phenomenon in 2025, pulling Netflix viewership into territory the platform rarely sees for an animated feature. The songs chart. The merchandise sells out.…",
    date: "Apr 9, 2026",
    category: "Korea VC",
    readTime: "6 min",
    canonicalUrl: "https://ethancho12.substack.com/p/for-non-korean-lps-why-korea-is-the",
    slug: "for-non-korean-lps-why-korea-is-the-most-mispriced-startup-m",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "startup", "mispriced", "market", "korean", "korea"],
    wordCount: 1163,
    rating: 3,
    content: `Consider a counterfactual. K-pop Demon Hunters becomes a global phenomenon in 2025, pulling Netflix viewership into territory the platform rarely sees for an animated feature. The songs chart. The merchandise sells out. The IP gets optioned across three continents.

[![](https://substackcdn.com/image/fetch/$s_!MCBl!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3232e04e-ad17-40ff-86b6-792353cc834b_2572x1100.jpeg)](https://substackcdn.com/image/fetch/$s_!MCBl!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3232e04e-ad17-40ff-86b6-792353cc834b_2572x1100.jpeg)

Now run the same scenario with one variable changed. The same script, the same animation studio, the same voice cast, the same music. But the commissioning platform is TVing, a Korean domestic streaming service. Under that scenario, the project ends as a children’s program on a weekend slot, closes after three weeks of middling ratings, and never leaves the peninsula. Same content. Same creative team. Different outcome by two orders of magnitude.

This thought experiment is the cleanest way to explain why Korea is the most mispriced startup market in Asia.

### **This is not a story about content.**

The counterfactual works because it isolates the variable that actually matters. The creative input was globally competitive. The distribution channel was the bottleneck. When the content was routed through a global channel, it cleared global prices. When it would have been routed through a domestic channel, it would have cleared domestic prices. The gap between those two prices is the arbitrage.

The same gap exists across Korean technology companies right now. Korean founders are building products that compete credibly against US and Chinese peers. Korean capital markets, Korean M&A activity, and Korean IPO valuations are not. When an analyst in Boston or New Haven looks at Korean VC returns on a spreadsheet, what they see is the domestic distribution channel, not the underlying content.

They are watching TVing, not Netflix.

### **What US endowments are actually measuring**

The standard objections to Korean VC allocation are familiar to anyone who has sat across from a CIO. Fund sizes are too small for meaningful ticket deployment. Exit comparables come back weak because the IPO market discounts Korean listings by thirty to forty percent against global peers. Prior experience with Korean funds produced disappointing net multiples. Governance and reporting quality trails what an endowment expects from a 2018 vintage European or Israeli fund. Currency hedging eats into returns.

***Every one of these objections is defensible. None of them measure founder quality. They measure the channel that Korean founders historically had no choice but to use.***

That is the mispricing. An endowment is not refusing to pay for Korean founders because Korean founders are weak. It is refusing to pay because the exit channel is weak, and it has been pricing the two together as if they were inseparable. They are no longer inseparable. Samsung is not the only distribution path anymore. Kosdaq is not the only liquidity venue anymore. A Korean founder with the right background can now build a company that routes entirely through US capital markets, US customers, and US acquirers, while keeping engineering and operating leverage in Seoul at a fraction of the cost.

### **Founder Intelligence and the arbitrage pattern**

At TheVentures, I have spent the past several years formalizing what I call Founder Intelligence, the investment thesis that the durable edge in Korean venture is not sector, not technology, and not timing, but a specific founder profile that combines high-context Korean social fluency with American-style execution velocity.

The Korean Diaspora founder sits at the intersection of two operating systems that rarely coexist in one person. One operating system is Korean: dense network access, engineering talent inside the country, cost discipline inherited from growing up in a brutally competitive domestic market, and the social capital to recruit senior Samsung or Naver engineers on trust alone. The other operating system is American: comfort with venture-scale ambition, willingness to burn capital against a clear plan, native English go-to-market fluency, and a board-management instinct shaped by US norms.

Almost every globally scaled Korean-origin company of the last decade has been built by a founder with both operating systems active. Coupang. Sendbird. Moloco. Lunit. The ones that stayed inside one operating system stayed inside the domestic channel, and their cap tables priced accordingly. The ones that bridged both scaled onto global channels, and their cap tables priced accordingly.

The investment thesis is narrower than “back Korean startups” and sharper than “back Korean-Americans.” It is this: back Korean-origin founders who can operate in both contexts simultaneously, and enter their cap tables at Korean seed and Series A prices before the global channel repricing happens.

### **Why the gap has not closed**

The reasonable question from any endowment CIO is this. If the mispricing is real, why has it not already been arbitraged away by smarter local capital?

Three reasons.

First, Korean LPs, who fund the majority of Korean VC, optimize for policy and stability mandates rather than global outlier returns, which means most Korean fund strategies are designed to look defensible to a domestic LP committee, not to catch a Coupang.

Second, US-based funds that could play this arbitrage do not have sourcing density in Seoul and treat Korea as an occasional flyer rather than a primary hunting ground.

Third, the founder pool this thesis depends on, Korean-origin operators with both operating systems active, was too small a decade ago and has only recently reached the density required to support a dedicated strategy.

The window that produced the mispricing is the same window that is closing it. An endowment that takes a position in the next twenty four months is participating in the repricing. An endowment that waits five years is buying after it.

### **What this means for a US endowment allocator**

The ask is narrow and specific. Not a blanket Korea allocation. Not a fund of Korean funds. A direct exposure to the Korean-origin founder cohort that is already routing through global channels, sourced by a GP with full context on both operating systems and a portfolio concentrated on the founder profile described above.

If that framing is interesting enough to pressure test against your current Asia allocation, I will make the case directly. The data I would bring to that conversation is not public, and it should not be. It is the part of the thesis that does not belong in a newsletter.

---

*Ethan Cho (조여준) is Chief Investment Officer at TheVentures, a Seoul-based early-stage venture capital firm founded by the co-founders of Viki (acquired by Rakuten). His investment career spans Google Korea, Qualcomm Ventures, Samsung Strategy and Innovation Center, KB Investment, and Fast Ventures, with early investments in Toss and Dunamu. He holds a BBA from Seoul National University and an MBA from Columbia Business School, and is a licensed Korean CPA.*`,
  },

  {
    title: "When the Myth Arrives, Something Dies",
    titleKo: "신화가 도착하면 죽는 것들",
    excerpt: "지금 테크 쪽 컨텐츠를 쓰는 사람들은 온통 Mythos 성능 미쳤다 라는 소리만 질러대고 있다. 이해한다. 그래야 FOMO가 생기니까. 화이팅!",
    date: "Apr 8, 2026",
    category: "Hot Takes",
    readTime: "6 min",
    canonicalUrl: "https://ethancho12.substack.com/p/43f",
    slug: "when-myth-arrives-something-dies",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "something", "arrives"],
    wordCount: 1233,
    rating: 3,
    content: `지금 테크 쪽 컨텐츠를 쓰는 사람들은 온통 Mythos 성능 미쳤다 라는 소리만 질러대고 있다. 이해한다. 그래야 FOMO가 생기니까. 화이팅!

나는 좀 더 안쪽으로 파고들어 보려 한다. 성능이 아닌 시사점들 위주로.   
지난번 글이 매콤했다면 오늘 글은 좀 쓰다.  
옆에 박하사탕 하나 정도 준비해둬도 좋을 듯 하다.

Anthropic이 새로운 모델 Mythos를 발표하려다가 멈췄다. 뚜껑을 열어보니 너무 강력해서 지금까지 사람들이 사용하던 프로토콜들을 전부 무력화 가능하다는 무서운 사실을 발견한 것이다.

[![](https://substackcdn.com/image/fetch/$s_!va0c!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fdead8470-2b6c-4ec0-b4d1-9d94b8337476_3840x2160.png)](https://substackcdn.com/image/fetch/$s_!va0c!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fdead8470-2b6c-4ec0-b4d1-9d94b8337476_3840x2160.png)

그래서 Anthropic은 Mythos를 Preview 버젼으로 제한했다. Anthropic은 현재로서 이 모델을 일반에 풀 생각이 없다. 발표문에 “일반 공개 계획 없음”이라고 못박혀 있다. 대신 Project Glasswing이라는 이니셔티브를 만들어 12개 조직에만 접근권을 줬다.

[![](https://substackcdn.com/image/fetch/$s_!Y8nb!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7b06c69c-8b53-4d4c-9b2c-ee31b17da85c_2614x1506.png)](https://substackcdn.com/image/fetch/$s_!Y8nb!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7b06c69c-8b53-4d4c-9b2c-ee31b17da85c_2614x1506.png)

12명의 명단은 이렇다. AWS, Google, Microsoft, Apple, NVIDIA, Broadcom, Cisco, CrowdStrike, Palo Alto Networks, Linux Foundation, JPMorganChase, 그리고 Anthropic 본인.

빠진 이름이 더 많은 시사점을 준다.   
OpenAI가 없고, Meta가 없고, Oracle도 없다. 중국, 유럽, 한국, 일본, 인도 기업도 한 곳도 없다. 그리고 미국 정부도 없다. 미국 정부는 “ongoing discussions” 자리에 있을 뿐, 12명의 자리에는 앉지 못했다.

### 이 명단의 진짜 의미

Anthropic은 이 명단을 보안 이니셔티브의 파트너 명단으로 발표했다. 그러나 이 명단은 의도하지 않은 다른 문서이기도 하다. AI가 가장 늦게 대체할 자들의 명단.

생각해보면 단순하다. Anthropic은 AI 회사다. 모든 것을 AI로 대체하는 게 그들의 사업이다. 그런 그들이 1억 달러 사용 크레딧을 걸고 12명에게 “이건 너희가 해줘야 한다”고 부탁했다. 자기 모델로 대체할 수 있었다면 직접 했을 것이다. AI 회사가 자기 부정을 한 명단이고, 그래서 이 명단은 AI 시대 생존 영역의 가장 정직한 지도다. 본인들이 인정한 것이기 때문이다.

그런데 이 명단은 매우 한정적이다.

12개라는 숫자가 작다는 게 아니라 12개의 버티컬이 한정적이라는 뜻이다. 인터넷 토대, 칩, 네트워크 장비, 보안, 결제, 운영체제 거버넌스. 한 줄로 요약하자면 이미 수십 년 전에 자리를 잡은 시스템 인프라다. Cisco는 1984년 창업이다. Microsoft는 1975년이다. Linux 커널은 1991년에 시작됐다. JPMorgan의 뿌리는 1799년까지 거슬러 올라간다. 신규 진입이 사실상 닫힌 자리들이다.

지난 몇 년간 AI 시대 생존론은 대체로 이런 모양이었다.   
AI에 대체되지 않으려면 깊은 해자를 만들어라. 워크플로우 안에 박혀라. 데이터를 쌓아라. 듣기에 좋다. 그러나 Anthropic의 12명 명단은 이 처방의 한계를 같이 보여준다. 해자는 새로 만드는 게 아니라 이미 가지고 있는 것이다. 1985년에 Cisco를 창업한 사람과 2025년에 SaaS를 창업한 사람은 같은 선상에 있지 않다.

### 단위가 바뀌었다

이 패턴 자체는 새롭지 않다. 지난 200년간 빈 회의부터 얄타까지, 강대국이 세계 질서를 다시 그릴 때마다 같은 일이 반복됐다. 매번 10명에서 15명 사이의 명단이 발표됐고, 그 명단에 들어간 자는 다음 30년의 규칙을 만들었다. 들어가지 못한 자는 그 규칙을 받았다. 그 회의들에 조선은 어디에도 못 들어갔고, 그게 1910년의 결과로 이어졌다. 한국인이 모를 수 없는 패턴이다.

[![](https://substackcdn.com/image/fetch/$s_!G5l7!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3fbb271b-c9ec-42e2-8d6f-96aa6cf75c06_650x495.jpeg)](https://substackcdn.com/image/fetch/$s_!G5l7!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3fbb271b-c9ec-42e2-8d6f-96aa6cf75c06_650x495.jpeg)

새로운 건 단위다. 19세기 회담의 자리에는 국가가 앉았다. 빈에 영국 외무장관이 갔고, 베를린에 비스마르크가 의장을 맡았고, 베르사유에 미국 대통령이 직접 갔다. 그래서 못 들어간 나라가 할 일도 명확했다. 국가를 강하게 만드는 것. 산업을 일으키고 군대를 키우고 외교를 하는 것. 모든 정답이 국가 단위에 있었다.

Project Glasswing의 12명에는 미국 정부가 없다. 자리에 앉은 건 12개 기업이다. 세계 최강대국의 정부조차 이 회담에서는 옵저버다. Anthropic이 누구를 명단에 넣을지 정한다. 미국 의회가 아니다. 백악관이 아니다. 한 AI 회사의 경영진이 결정한다. 그리고 그 결정에 따라 다음 30년의 사이버 인프라 표준이 정해진다.

다음 시대의 회담은 단위가 국가에서 기업으로 바뀌었다. 명단에 들어가려면 정부가 강한 게 아니라 기업이 강해야 한다. 그것도 그냥 규모만 큰 기업이 아니라 세계적으로 완전히 대체 불가능한 기업이어야 한다.

### 한국 정부가 잘못한 게 아니다

먼저 분명히 해두자. 한국이 지난 60년간 정부 주도 산업 정책으로 성장했다는 사실은 비판의 대상이 아니다. 중화학공업, 초고속 인터넷, 그리고 지금의 K-반도체와 K-AI까지. 명단의 단위가 국가였던 시대에 정부가 직접 그림을 그리는 것은 합리적이었고, 한국은 그 합리성으로 기적을 만들었다. 다른 어떤 후발 국가도 같은 시기에 같은 결과를 내지 못했다. 이건 이론이 아니라 결과다.

문제는 능력이 아니라 게임이 바뀐 것이다.

1970년대 중공업 정책의 도구가 1990년대 IT에 그대로 안 맞았던 것과 비슷하다. 그때도 정부는 빠르게 도구를 바꿨다. 지금 또 그래야 할 시점이다.

### 한국의 명단을 채우려 하면

Glasswing 12명의 카테고리에 한국 등가물을 넣어보면 10명까지 채워지고 두 자리가 빈 채로 남는다. 클라우드의 네이버, 메모리의 삼성전자와 SK하이닉스, 통신의 KT, 플랫폼의 카카오, 금융의 국민은행, 전력의 한국전력, 보안의 안랩, 결제의 금융결제원, 자본시장의 한국거래소. 여기까지가 10명이다. 빈 두 자리는 네트워크와 반도체 인프라, 그리고 오픈소스 거버넌스다. 한국에는 Cisco도 Broadcom도 Linux Foundation도 없다.

이 명단이 보여주는 것은 세가지다.

첫째, 두 자리가 비어 있다. 한국 IT 인프라의 두 층이 외국 장비와 외국 거버넌스 위에서 돈다.

둘째, 채워진 10명 중 세 곳이 정부 또는 정부 산하다. 한국전력, 금융결제원, 한국거래소. 미국 명단에는 정부 기관이 단 한 곳도 없다. 한국의 시스템층이 역사적 이유로 민간보다 정부와 정부 산하를 통해 운영돼왔다는 사실의 반영이다.

셋째, 채워진 10명조차 한 단계 들여다보면 미국 12명의 하위 노드에 가깝다. 네이버 클라우드는 Linux 위에서 돌고, 삼성전자의 반도체 설계는 미국 EDA 툴 위에서 돈다. 한전 OT 시스템에는 Cisco 장비가 들어가고, 국민은행 엔드포인트는 CrowdStrike 류의 미국 솔루션에 의존한다. 한국 안에서는 가장 안쪽 자리지만 글로벌 시스템층에서는 가장자리에 서 있다.

### 그래서 다 국산화하자는 얘기가 아니다

여기까지 읽으면 자연스러운 결론이 떠오른다. 한국 인프라를 다 국산화하자. 자체 클라우드, 자체 칩, 자체 네트워크, 자체 OS.

그러나 이 결론은 틀렸다.

시스템층은 글로벌 단일 표준이 효율의 핵심이고, 한국이 그 표준의 하위 노드인 것 자체는 문제가 아니다. 일본도 독일도 영국도 같은 자리에 있다. 그게 21세기 IT의 기본 구조다.

진짜 문제는 표준 그 자체가 아니다. 다른 두 가지다.

하나는 표준 위에 얹혀 있는 한국 고유의 로컬 레이어다. 한국어 인증, 한국 규제 대응, 한국 의료 데이터, 한국 행정 시스템. 이 층은 글로벌 시스템 12명의 시야 바깥에 있다. 그들이 만들지도 보호하지도 않는다. 노관심의 영역이다. 그런데 이 층이 무너지면 한국 시스템이 무너진다. 시장이 작아 글로벌 자본은 들어오지 않고, 안보 차원에서 외국 자본이 들어오는 것도 적절하지 않다. 자국 자본만이 채울 수 있는 빈 시장이 정확히 여기 있다.

다른 하나는 한국 기업 한두 곳이 글로벌 시스템층 명단에 직접 박히는 일이다. 모든 카테고리를 다 채우려는 게 아니다. 메모리에서 삼성전자가 이미 한 자리를 가졌듯이, 다른 한두 카테고리에서 한국 기업 하나가 글로벌 12명 안에 들어가는 길. 이건 국산화의 정반대로 글로벌화다. 한국 안에서 보호받으며 자라는 게 아니라 한국 밖으로 나가서 글로벌 표준의 일부가 되는 것.

이 두 갈래가 다음 시대의 명단을 마주하는 진짜 답이다. 안에서 지키는 자본과 밖에서 자리를 만드는 자본. 둘 다 자국 자본의 일이고, 둘 다 정부가 그림을 직접 그리는 일이 아니라 가장 긴 호흡으로 서 있는 LP의 일이다. 새 게임에서 정부의 역할은 그림 그리는 자에서 가장 장기적인 안목을 가진 LP로 옮겨가는 것이다. 미국 시스템층 12명 중 상당수가 초기에 국방부, NSF, DARPA의 자금을 거쳤다. 다만 그 자금이 기업의 자리를 대신 만들지는 않았다. 기업이 자기 자리를 만들고 자금이 그 뒤에 서서 버텨줬다.

### 클로징

베를린, 얄타, 포츠담에 못 들어간 나라의 후예가, 다음 회담의 단위가 바뀌었다는 사실을 가장 빨리 알아채야 한다. 회담이 기업 단위로 바뀌었다면 한국이 보낼 자리도 기업이어야 한다. 정부의 역할은 그 기업 뒤에 30년간 서 있는 일이다.

한국 정부가 후발주자 시대에 보여준 놀라운 적응력이 한 번 더 필요한 자리에 와 있다.`,
  },

  {
    title: "[For Non-Korean LPs] The Inverted Risk Curve",
    excerpt: "[](https://substackcdn.com/image/fetch/$s!uaKW!,fauto,qauto:good,flprogressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F21c1bcab-f0b3-47cc-95b6-331ebcea1559330x153.jpeg)",
    date: "Apr 8, 2026",
    category: "Korea VC",
    readTime: "4 min",
    canonicalUrl: "https://ethancho12.substack.com/p/for-non-korean-lps-the-inverted-risk",
    slug: "for-non-korean-lps-the-inverted-risk-curve",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "curve", "inverted", "korean"],
    wordCount: 891,
    rating: 3,
    content: `[![](https://substackcdn.com/image/fetch/$s_!uaKW!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F21c1bcab-f0b3-47cc-95b6-331ebcea1559_330x153.jpeg)](https://substackcdn.com/image/fetch/$s_!uaKW!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F21c1bcab-f0b3-47cc-95b6-331ebcea1559_330x153.jpeg)

Walk into a Sand Hill Road partner meeting and the question is: who left Stripe last quarter, and how do we get into their seed round before anyone else hears the name. Walk into a Yeouido investment committee and the question is: how many times is this Pre-IPO secured against downside, and what is the redemption clause if the listing slips past 2027.

[![](https://substackcdn.com/image/fetch/$s_!rdr2!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F50a36806-b755-42ae-9d55-20820cb6fcd9_275x183.jpeg)](https://substackcdn.com/image/fetch/$s_!rdr2!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F50a36806-b755-42ae-9d55-20820cb6fcd9_275x183.jpeg)

These are not two cultures investing in the same asset class with different styles. They are two financial systems that have placed their bets at opposite ends of the risk curve. American venture capital concentrates its conviction at the earliest, most uncertain moment. Korean institutional capital concentrates its conviction at the latest, most certain moment. The inversion is structural, and once you see the cause, the behavior of every deal in both markets becomes predictable.

### The cause is the LP, not the GP.

[![](https://substackcdn.com/image/fetch/$s_!7S1l!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1d2e7a79-3c6f-4e22-ba2f-ca000456cf67_1200x1500.webp)](https://substackcdn.com/image/fetch/$s_!7S1l!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1d2e7a79-3c6f-4e22-ba2f-ca000456cf67_1200x1500.webp)

In the United States, the dominant venture LP is the university endowment, the family office, and the pension fund willing to lock capital for ten to fifteen years against the explicit expectation that most funds will return modestly and a few will return everything. The power law is not a belief in Silicon Valley. It is a budgeted assumption. Yale does not call Sequoia after a down year and ask for a redemption schedule.

In Korea, the dominant LP is 모태펀드 (the Korea Fund of Funds) and its policy-fund cousins, evaluated by the National Assembly and the Board of Audit. Their fiduciary frame is not “did you generate alpha across the portfolio.” It is “did this specific fund return its principal with a multiple, and if not, who is responsible.” A Korean GP whose fund liquidates below 1.0x does not get to raise the next one. Often the firm itself does not survive. Variance is not rewarded here. Variance is treated as negligence.

### That single fact reorganizes everything downstream.

If your LP measures you on every fund’s liquidation multiple, you cannot run a portfolio where eight of ten investments go to zero. You need eight of ten to return two times. The only way to engineer that distribution at scale is to invest after product-market fit is proven, after revenue is contracted, after the IPO underwriter is selected, and to wrap each check in redeemable convertible preferred shares with put options, ratchet clauses, and IPO-failure penalties. That is not risk capital. That is structured private credit dressed in venture clothing.

If your LP is Yale, you can do the opposite. You can pay forty million dollars for eight percent of a six-person company because you know that one such position every five years pays for the entire fund. You will lose money on most of these checks. Yale knows. Yale signed up for it in writing.

I call this the Risk Capital Inversion, and it is the single most important thing a non-Korean LP needs to understand before allocating to a Korean fund. ***The Korean venture market is not undercapitalized. It is miscapitalized.*** The capital that exists is structurally prohibited from doing what venture capital is supposed to do, which is buy uncertainty cheaply and hold it long enough for the math to work.

***This is also the opportunity. A Korean fund backed by LPs who do not require quarterly downside-protected reporting, who accept the power law in writing, who measure returns at the portfolio level rather than the fund level, can do in Korea what American funds did in Silicon Valley a generation ago.***

Not because the founders are absent. The founders are there. I have spent twenty years watching them. The capital structure to back them properly is what has been missing.

That is the gap TheVentures was built into, and it is the gap our AI Fund is being raised to fill.

---

*Ethan Cho (조여준) is Chief Investment Officer at TheVentures, a Seoul-based early-stage venture capital firm founded by the co-founders of Viki (acquired by Rakuten). His twenty-year career includes Google Korea, Qualcomm Ventures, Samsung Strategy & Innovation Center, KB Investment, and Fast Ventures, with early investments in Toss and Dunamu. He holds an MBA from Columbia Business School and is ranked the #1 Korean voice on LinkedIn by Favikon.*`,
  },

  {
    title: "Kakao's 'Focus and Choice' Is a Polite Name for Diversification Failure",
    titleKo: "카카오의 “선택과 집중”은 다각화 실패를 예쁘게 쓴 말이다",
    excerpt: "[](https://substackcdn.com/image/fetch/$s!4GNg!,fauto,qauto:good,flprogressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1509b65c-7e48-4f60-a421-4b8dacb4482b1920x1080.jpeg)",
    date: "Apr 2, 2026",
    category: "Market Analysis",
    readTime: "5 min",
    canonicalUrl: "https://ethancho12.substack.com/p/5ab",
    slug: "kakao-focus-diversification-failure",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "choice'", "diversification", "polite", "kakao's", "'focus", "failure"],
    wordCount: 1005,
    rating: 3,
    content: `[![](https://substackcdn.com/image/fetch/$s_!4GNg!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1509b65c-7e48-4f60-a421-4b8dacb4482b_1920x1080.jpeg)](https://substackcdn.com/image/fetch/$s_!4GNg!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1509b65c-7e48-4f60-a421-4b8dacb4482b_1920x1080.jpeg)

카카오가 계열사를 정리하고 있다. 147개였던 계열사가 88개로 줄었다. 게임즈는 라인야후에 넘겼다. 다음은 업스테이지에 지분 교환으로 줬다. 카카오헬스케어는 차바이오텍에 매각했다. 카카오VX도 내놨는데 매수자 자금 조달이 안 돼서 무산됐다.

카카오모빌리티는 더 복잡하다. IPO가 무산된 뒤 TPG, 칼라일 등 재무적 투자자들이 8년째 엑시트를 못 하고 있다. VIG 컨소시엄이 소수지분 인수를 추진했지만 무바달라가 “6조는 너무 비싸다”며 빠졌다. 그리고 이번 주, 우버가 경영권 인수 의향서를 전달했다는 보도가 나왔다. 카카오모빌리티는 “사실무근”이라고 부인했지만, TPG 매각 측은 우버, 그랩, VIG 등 복수의 후보와 동시에 협상을 이어가고 있는 것으로 알려져 있다. 카카오엔터테인먼트 매각도 거론된다.

정신아 대표는 이렇게 설명한다. “카카오톡을 중심으로 AI로 재편된 핵심 사업 전략을 속도감 있게 추진하겠다.” 시장에서는 이걸 “선택과 집중”이라고 부른다.

[![](https://substackcdn.com/image/fetch/$s_!x8NV!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0ea75d21-bd40-41fb-a5d8-40c30278dd4f_259x195.jpeg)](https://substackcdn.com/image/fetch/$s_!x8NV!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0ea75d21-bd40-41fb-a5d8-40c30278dd4f_259x195.jpeg)

멋있는 말이다. 그런데 순서를 거꾸로 읽으면 뜻이 달라진다.

카카오모빌리티 IPO를 추진했다. 공정위가 콜 몰아주기로 과징금을 때렸다. 무산됐다. SM엔터 인수를 밀어붙였다. 김범수가 시세조종 혐의로 구속됐다. 카카오VX를 팔려고 했다. 살 사람이 돈이 없었다. 모빌리티 FI 지분을 넘기려 했다. 무바달라가 가격이 맞지 않는다며 떠났다. 다음을 매각했다. 노조가 “헌신짝처럼 버린다”며 비상대책회의를 열었다.

하나씩 터지니까 하나씩 치운 것이다. 전략이 아니라 수습이다. “비핵심 계열사 정리”는 다각화 실패를 투자자가 듣기 좋게 포장한 표현이다.

---

카카오의 원래 전략은 분명했다. 카카오톡이 한국인의 생활 전체를 관통하는 슈퍼앱이 되는 것. 택시를 부르고, 송금을 하고, 웹툰을 보고, 쇼핑을 하고, 대리운전을 부르는 것. WeChat 모델이다.

[![](https://substackcdn.com/image/fetch/$s_!Umbd!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3d03dd29-1b1f-4dde-beb6-0165059fc679_284x177.jpeg)](https://substackcdn.com/image/fetch/$s_!Umbd!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F3d03dd29-1b1f-4dde-beb6-0165059fc679_284x177.jpeg)

문제는 WeChat이 성공한 전제 조건이 한국에 없다는 것이다. 중국은 폐쇄 생태계다. 구글도 없고 페이스북도 없다. 결제 인프라를 텐센트와 알리바바가 양분한다. 한국은 다르다. 공정위가 독점을 잡고, 정치권이 골목상권을 거론하고, 택시기사가 반발하고, 노조가 총파업을 예고한다.

***카카오는 WeChat이 될 수 없는 나라에서 WeChat 전략을 10년간 밀었다. 그리고 실패했다.***

---

더 근본적인 문제가 있다. 카카오톡의 플랫폼 파워가 생각만큼 강하지 않았다.

카카오톡은 4,900만 명이 쓴다. 한국 인구의 95%다. 이 숫자만 보면 무적이다. 그런데 4,900만 명이 카카오톡에서 “하는 일”은 메시지를 보내는 것이다. 택시를 부를 때는 카카오T 앱을 따로 깔아야 한다. 쇼핑은 쿠팡에서 한다. 결제는 카카오페이를 쓰지만, 토스가 더 빠르게 치고 올라왔다. 뉴스는 네이버에서 본다.

***카카오톡은 트래픽의 입구였지 거래의 플랫폼이 아니었다. 사람들은 카카오톡을 통해 링크를 받고, 다른 앱으로 넘어갔다. 카카오톡 안에서 돈을 쓰는 구조가 만들어지지 않았다.***

DAU와 플랫폼 파워는 다른 것이다. DAU는 사람이 들어오는 빈도이고, 플랫폼 파워는 들어온 사람이 돈을 쓰는 구조다. 카카오는 이 둘을 같은 것으로 착각했다. 계열사를 붙여놓으면 카카오톡의 트래픽이 자동으로 매출로 전환될 거라고 봤다. 안 됐다. 카카오뱅크와 카카오페이가 그나마 성공한 건, 카카오톡 생태계의 시너지가 아니라 금융업이라는 독립된 규제 체계 안에서 각자도생했기 때문이다.

---

우버의 카카오모빌리티 인수설이 이 구조를 정확히 보여준다.

[![](https://substackcdn.com/image/fetch/$s_!gZOY!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5938bacf-e3ec-440b-8af7-e3e151b24308_275x183.jpeg)](https://substackcdn.com/image/fetch/$s_!gZOY!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5938bacf-e3ec-440b-8af7-e3e151b24308_275x183.jpeg)

우버가 카카오모빌리티에 관심을 보이는 이유는 카카오톡과의 시너지가 아니다. 카카오T가 한국 택시 호출 시장의 90%를 점유하고 있기 때문이다. 우버에게 카카오모빌리티는 “카카오의 자회사”가 아니라 “한국 시장 진입 티켓”이다. 카카오톡이 없어도 카카오T는 돌아간다. 실제로 카카오T는 별도 앱이고, 카카오톡 안에서 택시를 부르는 사람보다 카카오T 앱을 직접 여는 사람이 훨씬 많다.

카카오가 10년간 구축했다고 믿은 “생태계 시너지”는, 매수자의 눈에는 존재하지 않는 것이다. 우버든 그랩이든 VIG든, 이들이 사려는 것은 “카카오의 생태계”가 아니라 “시장 점유율”이다.

***카카오톡과 분리해도 가치가 유지되는 자산. 역설적으로, 이것이 카카오톡 중심 생태계 전략이 실패했다는 가장 분명한 증거다.***

---

이제 카카오에 남는 것은 카카오톡과 AI다. 그런데 AI 전략을 들여다보면 불안한 게 아니라, 전략 자체가 안 보인다.

[![](https://substackcdn.com/image/fetch/$s_!W27S!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F9bded713-d801-4e0e-8d46-4bb802098580_293x172.jpeg)](https://substackcdn.com/image/fetch/$s_!W27S!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F9bded713-d801-4e0e-8d46-4bb802098580_293x172.jpeg)

AI 시대에 플랫폼 기업이 해야 할 가장 중요한 결정은 파트너십이다. 누구의 모델을 쓸 것인가, 어떤 레이어에서 싸울 것인가, 자체 기술과 외부 기술의 경계를 어디에 그을 것인가. 이 선택이 향후 5년의 경쟁 구도를 결정한다.

카카오의 행보를 보면 갈피를 못 잡고 있다. 오픈AI와 전략적 제휴를 맺었다. 다음을 업스테이지에 넘기면서 솔라 기반 검색 전환을 기대한다. 국가대표 AI 프로젝트에서는 탈락했다. 자체 LLM은 없다. 네이버는 하이퍼클로바X로 방향을 잡았고, 삼성은 가우스로 디바이스 AI에 집중한다. 카카오는 오픈AI 쪽도 보고, 업스테이지 쪽도 보고, 그러면서 자체 온디바이스 AI도 이야기한다. 하나를 깊게 파는 게 아니라 여러 개를 얕게 건드리고 있다.

AI에서 파트너십은 결혼에 가깝다. 기술 스택이 엮이고, 데이터 파이프라인이 연결되고, 제품 로드맵이 동기화된다. 한번 들어가면 바꾸기가 극도로 어렵다. 그런데 카카오는 아직 누구와 결혼할지를 정하지 못한 채로 여러 명과 동시에 소개팅을 하고 있는 모양새다.

---

카카오의 진짜 위기는 계열사가 줄어드는 것이 아니다. 카카오톡이라는 파이프에 흐르는 물이 없어지는 것이다. 슈퍼앱의 핵심은 한 앱에서 모든 걸 해결하는 편의성이었다. 그 편의성을 제공하는 서비스들을 전부 팔아버리면, 카카오톡은 메신저로 돌아간다. 2012년으로.

“선택과 집중”이라는 말은 버릴 것을 골랐다는 뜻이다. 카카오가 지금 해야 할 질문은 “뭘 버릴까”가 아니라 “남은 것으로 뭘 할 수 있는가”다. 그 답이 나오기 전까지, 계열사 정리는 전략이 아니라 그저 청산일 뿐이다.

---

나는 카카오의 AI 전략에 대해 나름의 생각이 있다. 카카오에서 별도로 미팅 요청이 온다면 정리해서 공유할 의향이 있다. 아마도 연락이 안 올 거다. 원래 질문을 하려면 자기 생각부터 있어야 하니까.

듣기 싫겠지만, 사실이다.`,
  },

  {
    title: "The Code Is Safe. We Are Not.",
    titleKo: "우리 코드는 안전한데 우리는 불안전해요",
    excerpt: "Anthropic이 이상하다.",
    date: "Apr 1, 2026",
    category: "AI Investing",
    readTime: "5 min",
    canonicalUrl: "https://ethancho12.substack.com/p/dae",
    slug: "code-safe-we-are-not",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle"],
    wordCount: 1001,
    rating: 3,
    content: `Anthropic이 이상하다.

3월 26일, 내부 파일 약 3,000개가 공개 캐시에서 발견됐다. 미출시 모델 “Mythos”의 블로그 초안까지 포함돼 있었다. 5일 뒤인 3월 31일, Claude Code의 전체 소스코드 50만 줄이 npm 패키지에 실려 나갔다. 디버깅용 source map 파일을 배포 빌드에서 빼지 않은 것이다. 44개 미출시 기능의 feature flag, 시스템 프롬프트, 아키텍처 전체가 공개됐다. 몇 시간 만에 GitHub에서 41,500번 fork됐다.

[![](https://substackcdn.com/image/fetch/$s_!lHg3!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd74fb435-e707-435f-95df-368abc14a63b_455x452.webp)](https://substackcdn.com/image/fetch/$s_!lHg3!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd74fb435-e707-435f-95df-368abc14a63b_455x452.webp)

프로젝트명 카피바라 = Mythos

같은 주에 피크 타임 토큰 한도도 줄였다. $100/월 Max 플랜 유저가 1시간 만에 한도를 소진했다는 불만이 쏟아지고 있다.

회사의 공식 입장은 매번 같다. “사람의 실수. 보안 침해 아님.”

한 번은 실수다. 그런데 이번이 두 번째다. 2025년 2월에도 거의 같은 source map 유출이 있었다. 14개월 간격으로 같은 실수를 두 번 했다는 건 프로세스가 없다는 뜻이다.

이 상황을 네 가지 렌즈로 본다.

---

**Lens 1. 회계: 누가 돈을 버는가**

Anthropic의 성장 숫자 자체는 압도적이다. 2026년 3월 기준 연간 매출 런레이트 $19B. 2025년 말 $9B에서 두 배. Claude Code만 ARR $2.5B. Fortune 10 기업 중 8개가 고객이다.

그런데 이 숫자에 함정이 있다.

Anthropic은 Amazon, Google 등 하이퍼스케일러로부터 받는 클라우드 크레딧을 매출에 포함시키고 있다. Bank of America 추정으로 2026년 클라우드 결제 규모만 $6.4B이다. 이건 현금이 들어오는 매출이 아니라, 클라우드 크레딧을 매출로 잡은 것이다.

[![](https://substackcdn.com/image/fetch/$s_!KabD!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5e884b37-6fb4-4c3e-8ea4-9ce186b842c7_2816x1536.png)](https://substackcdn.com/image/fetch/$s_!KabD!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5e884b37-6fb4-4c3e-8ea4-9ce186b842c7_2816x1536.png)

SEC가 순매출 인식으로 변경을 요구하면 헤드라인 숫자가 크게 줄어든다. $19B이 실제로는 얼마인가. Khosla Ventures 파트너도 공개적으로 지적했다. “Anthropic과 OpenAI가 둘 다 IPO하면, 같은 성격의 매출을 다르게 회계 처리하는 걸 SEC가 그냥 놔두겠느냐.”

소스코드 유출과 직접 관련은 없다. 하지만 회계 렌즈로 보면, 이 회사의 “성장 서사”가 생각보다 복잡하다는 걸 알 수 있다. 겉으로 보이는 $19B과 실제 현금 창출 능력 사이에 간극이 있다.

---

**Lens 2. 빅테크: 플랫폼 파워는 누가 가졌는가**

Anthropic의 구조적 약점은 플랫폼 종속이다.

최대 투자자가 Amazon($8B+)과 Google($2B+)이다. 클라우드 인프라를 AWS와 GCP에 의존한다. 이 두 회사는 동시에 경쟁자이기도 하다. Amazon은 자체 모델 Nova를 밀고 있고, Google은 Gemini를 가지고 있다.

소스코드 유출이 이 구도에서 의미하는 바가 있다. 유출된 코드에는 Claude Code가 “context entropy” 문제를 해결하는 3계층 메모리 아키텍처, MEMORY.md 인덱스 시스템 등 Anthropic이 1-2년에 걸쳐 만든 핵심 기술이 담겨 있었다. 이건 모델 가중치가 아니라 모델을 “쓸모 있게” 만드는 소프트웨어 harness다.

[![](https://substackcdn.com/image/fetch/$s_!mQ5r!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe64ebbe3-f8f9-41eb-a1d1-348ab08bab93_300x168.jpeg)](https://substackcdn.com/image/fetch/$s_!mQ5r!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fe64ebbe3-f8f9-41eb-a1d1-348ab08bab93_300x168.jpeg)

Amazon과 Google이 이 코드를 분석하지 않을 이유가 없다. 투자자이면서 경쟁자인 빅테크가, 투자한 회사의 핵심 아키텍처를 공개 npm에서 무료로 받아볼 수 있게 된 것이다.

Anthropic은 모델은 잘 만든다. 그런데 모델을 감싸는 인프라와 운영에서 빅테크 수준의 성숙도가 없다. .npmignore 한 줄 관리 못하는 빌드 파이프라인이 그 증거다. 빅테크는 이런 실수를 하지 않는다. 수만 명의 엔지니어가 CI/CD 자동화를 10년 넘게 다듬어 왔으니까.

---

**Lens 3. 글로벌: 시장 배포와 데이터 독점**

Anthropic의 엔터프라이즈 침투 속도는 진짜 빠르다. Ramp Economics Lab 데이터에 따르면, 미국 기업의 OpenAI+Anthropic 합산 지출 중 Anthropic 비중이 2025년 초 10%에서 2026년 2월 65%까지 올랐다. 엔터프라이즈 API 시장 점유율도 OpenAI를 추월 중이다.

그런데 이번 유출은 이 엔터프라이즈 고객들에게 불편한 질문을 던진다.

[![](https://substackcdn.com/image/fetch/$s_!72vT!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd45a895d-4392-4f2b-9ba9-02f3c7589fdf_299x168.jpeg)](https://substackcdn.com/image/fetch/$s_!72vT!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd45a895d-4392-4f2b-9ba9-02f3c7589fdf_299x168.jpeg)

“safety-first”를 내세우는 AI 회사가 자기 코드를 npm에 실수로 공개했다. 고객 데이터가 나간 건 아니지만, 보안 프로세스의 수준이 드러났다. Fortune 10 기업 CISO가 이걸 보면 뭘 생각할까. 당장 계약을 끊지는 않겠지만, 다음번 벤더 리뷰에서 추가 질문은 당연히 나온다.

글로벌 확장 관점에서 더 큰 문제는 feature flag 44개가 공개된 것이다. 아직 출시하지 않은 기능들의 전체 로드맵이 경쟁사에게 노출됐다. Cursor, Windsurf, OpenAI Codex가 이 코드를 분석하고 있을 것이다. 전략적 서프라이즈가 사라졌다. 경쟁사 입장에서는 무료 엔지니어링 교육이자 무료 제품 로드맵이다.

---

**Lens 4. VC: 투자와 전략적 의미**

Anthropic은 Q4 2026, 빠르면 10월 IPO를 준비 중이다. $60B 이상 조달 목표. $380B 밸류에이션. Goldman Sachs, JPMorgan, Morgan Stanley가 주관사 경쟁 중이다.

이 타이밍에 일주일 만에 보안 사고 두 건이 터졌다.

IPO를 죽이는 사건은 아니다. 고객 데이터 유출도 아니고, 모델 가중치 노출도 아니다. 하지만 IPO는 숫자 반, 내러티브 반이다. Anthropic의 내러티브 핵심은 “safety-first AI company”다. 그런데 자기 빌드 파이프라인의 safety가 이 수준이라면, 그 내러티브의 신뢰도가 깎인다.

VC 관점에서 진짜 질문은 이것이다. hyper-growth 기업의 오퍼레이션이 성장 속도를 못 따라가는 건 흔한 일이다. 하지만 Anthropic은 “우리는 다르다”고 말해온 회사다. safety를 핵심 가치로 내세운다는 건, 기본적인 운영 안전에서도 높은 기준을 적용하겠다는 약속이다.

---

[![](https://substackcdn.com/image/fetch/$s_!DcYk!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F801eb3d8-e253-4df4-b156-ac372845c575_800x450.jpeg)](https://substackcdn.com/image/fetch/$s_!DcYk!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F801eb3d8-e253-4df4-b156-ac372845c575_800x450.jpeg)

그렇다고 한다

$19B 매출, $380B 밸류에이션인데 release checklist에 “source map 제거” 항목이 없었다. CI/CD 파이프라인에 한 줄 추가하면 되는 걸 14개월 동안 안 했다.

AI의 안전성을 연구하는 회사가, 그 연구 결과를 안전하게 보관하지 못하는 상황. 큰 것을 잘한다고 작은 것이 면제되지 않는다. 오히려 반대다. 작은 것에서 보이는 수준이 큰 것의 신뢰도를 결정한다.

공부를 아무리 잘해도 OMR 밀려 쓰면 끝이다.

그것도 두 번이나.`,
  },

  {
    title: "Why Korea May Lose the AI Race Even While Using AI Best",
    titleKo: "한국이 AI를 가장 잘 쓰고도 결국 패배할 수도 있는 이유",
    excerpt: "오늘 아침 SNS를 AI 주제 위주로 쭉 돌아봤다. 약간의 희망과 약간의 걱정이 섞이는 묘한 느낌이었다.",
    date: "Mar 26, 2026",
    category: "Korea VC",
    readTime: "7 min",
    canonicalUrl: "https://ethancho12.substack.com/p/ai-d53",
    slug: "why-korea-may-lose-ai-race-while-using-ai-best",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "while", "using", "korea"],
    wordCount: 1441,
    rating: 3,
    content: `오늘 아침 SNS를 AI 주제 위주로 쭉 돌아봤다. 약간의 희망과 약간의 걱정이 섞이는 묘한 느낌이었다.

희망적인 부분부터 이야기하자. 확실히 한국 사람들의 AI 툴 활용도가 빠르게 올라오고 있다. Techy한 신기술에 대해서는 세상 어느 나라보다 빠르다. 이럴 때는 옆 사람과 비교하는 습성이 긍정적으로 작동하는 아주 드문 케이스다. 옆사람이 관심을 기울이니까, 꽤 귀찮고 고통스러운 일일 텐데도 다들 어떻게든 배우고 어떻게든 뭔가를 만들어낸다. 멋지다.

그런데 우려되는 부분이 사실 더 크다.

[![](https://substackcdn.com/image/fetch/$s_!SzA7!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1c5f4ab5-a765-4ced-b8d5-8a3ff40fc85c_1500x844.jpeg)](https://substackcdn.com/image/fetch/$s_!SzA7!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F1c5f4ab5-a765-4ced-b8d5-8a3ff40fc85c_1500x844.jpeg)

만들어내는 결과물이 너무 기초적이다. 자랑한다고 올려놓은 프로덕트들을 보면, 솔직히 라스베리 파이 프로젝트 같은 느낌이다. 기술 시연으로서는 의미가 있지만, 누군가의 진짜 문제를 풀고 있는 건 아니다.

이건 툴의 한계가 아니다. 발상의 문제다.

**흑백개발자가 보여준 것**

[![](https://substackcdn.com/image/fetch/$s_!Bh7Y!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fcc3f03f4-ab45-47ac-8579-9e7639a8c00c_386x483.png)](https://substackcdn.com/image/fetch/$s_!Bh7Y!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fcc3f03f4-ab45-47ac-8579-9e7639a8c00c_386x483.png)

지난주 여의도에서 ‘흑백개발자 THE 해커톤’이 열렸다. 흑백요리사의 포맷을 개발자 버전으로 가져온 행사다. 국내 내로라하는 개발자 80명이 모여서 30시간 안에 시장에서 돈을 벌 수 있는 서비스를 만드는 대회였다. 토스 공동창업자 이태양, 실리콘밸리 유니콘 창업가 류기백 같은 사람들이 참여했고, 이준석 의원도 “하버드 출신 개발자의 실력을 보여주겠다”며 백 개발자로 참여했다. 에너지 음료를 마시며 밤을 새고, 팀원끼리 수익 모델을 놓고 논쟁을 벌이고, 노트북 타자 소리가 점점 커지는 장면. 대회 자체는 분명히 인상적이었다.

그런데 나오는 결과물을 보면 고개가 갸우뚱해진다.

[![](https://substackcdn.com/image/fetch/$s_!Sz-Z!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa711df1e-1dce-4f40-9d2c-37c326b5f722_1295x832.png)](https://substackcdn.com/image/fetch/$s_!Sz-Z!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa711df1e-1dce-4f40-9d2c-37c326b5f722_1295x832.png)

이준석 팀은 링크 공유 시 썸네일과 제목을 사용자가 직접 수정할 수 있는 도구 ‘fwd.page’를 만들었다. 온더룩 대표 이대범은 ‘AI에 대체될까 두려운 사람들’을 겨냥해서, 사용자 업무가 AI로 대체되기까지 남은 개월 수를 보여주고 구독을 유도하는 서비스를 개발했다. 팀원들끼리 “그렇게 하면 과금을 유도할 수 없다”, “서비스를 간단히 보여준 뒤 구독을 안내하는 게 낫다” 같은 논쟁을 벌이는 모습이 곳곳에서 눈에 띄었다고 한다.

한국 최고 수준의 개발자 80명이 모여서 30시간 동안 머리를 쥐어짰는데, 나온 것이 썸네일 편집기와 AI 공포 마케팅 구독 서비스다. 실력이 없어서가 아니다. 심사 기준 자체가 1주일 동안 발생한 실제 결제 금액과 깃허브 스타였으니, 당연히 빠르게 눈길을 끄는 B2C 아이템으로 갈 수밖에 없는 구조이긴 하다. 그래도 묻지 않을 수 없다. 이 사람들이 풀 수 있는 문제가 정말 이것뿐이었을까?

[![](https://substackcdn.com/image/fetch/$s_!4yJj!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7089aba8-dcd2-475e-8846-53f45609f55e_406x816.png)](https://substackcdn.com/image/fetch/$s_!4yJj!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7089aba8-dcd2-475e-8846-53f45609f55e_406x816.png)

이건 흑백개발자만의 문제가 아니다. 한국 AI 생태계 전체의 축소판이다.

**소비자 불편만 보이는 나라**

사람은 직접 불편을 겪어보기 전까지 문제를 인식하지 못한다. 원래 그렇게 되어 있다. 그런데 한국은 불편을 느낄 틈이 잘 없는 나라다. 배달은 30분 안에 오고, 택시는 앱으로 3분이면 잡히고, 은행 업무는 폰으로 다 된다. 소비자 입장에서 체감하는 마찰이 극도로 적다.

그래서 “AI로 뭘 만들어볼까” 하고 앉으면, 머릿속에 떠오르는 문제의 수준이 낮을 수밖에 없다. 이미 잘 돌아가는 것 위에 AI를 얹는 정도가 대부분이다. 없던 문제를 해결하는 게 아니라, 있는 것에 옷을 입히는 수준이다.

한국이 불편이 없는 나라라는 뜻이 아니다. 불편의 위치가 다를 뿐이다.

배달은 빠르지만 자영업자의 마진은 매년 깎인다. 결제는 편한데 그 뒤의 정산 구조는 엉망이다. 병원 예약은 쉬운데 의료 데이터는 병원마다 따로 놀고 있다. 관공서 민원은 온라인으로 되는데, 그 뒤에서 공무원은 여전히 수작업으로 서류를 넘기고 있다.

불편은 넘쳐난다. 소비자 눈에 안 보일 뿐이다.

[![](https://substackcdn.com/image/fetch/$s_!u6ZS!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F2daa3921-51e9-4e10-8462-2086f8404acc_2333x1162.png)](https://substackcdn.com/image/fetch/$s_!u6ZS!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F2daa3921-51e9-4e10-8462-2086f8404acc_2333x1162.png)

그런데 vibe coding으로 뭔가를 만들기 시작한 사람들 대부분이 B2C 경험밖에 없다. 본인이 소비자로서 겪은 것만 문제로 인식한다. 정산 시스템의 고통, 물류 허브의 비효율, 중소 제조업체의 발주 관리 지옥 같은 건 그 산업에 몸을 담가본 사람만 안다. 거기까지는 vibe coding이 데려다주지 못한다.

여기에 한국 특유의 “보여주기” 문화도 한몫한다. SNS에 올려서 반응을 받을 수 있는 건 눈에 보이는 앱이지, 백오피스 자동화가 아니다. 흑백개발자 해커톤의 심사 기준이 “1주일 매출”과 “깃허브 스타”인 것도 같은 맥락이다. 관객을 의식하는 순간, 결과물의 방향이 틀어진다.

**문제를 ‘잘 푸는 것’은 곧 하나도 안 중요해진다**

여기서 더 큰 그림을 봐야 한다.

문제를 잘 푸는 능력, 즉 실행력이라고 불리는 것의 가치가 빠르게 떨어지고 있다. 코드를 짜는 것, 디자인을 하는 것, 문서를 정리하는 것, 데이터를 분석하는 것. 이 모든 “잘 푸는” 영역을 AI가 대체하고 있고, 앞으로 더 빠르게 대체할 것이다.

흑백개발자 해커톤에서 토스 공동창업자 이태양은 개발에서 손을 뗀 지 10년 만에 복귀했는데, 본인 실력이 예전보다 오히려 좋아졌다고 말했다. 10년 전보다 손이 느려졌을 텐데 퍼포먼스가 올라간 이유는 하나다. AI가 실행을 대신 해주기 때문이다. 이제 코딩 실력 차이는 AI가 메워준다. 그러면 남는 건 뭐냐.

“무슨 문제를 푸느냐”다.

이건 AI가 대신 해줄 수 없다. AI는 주어진 문제를 기가 막히게 풀지만, 풀 만한 문제를 골라주지는 않는다. 어떤 문제가 진짜 문제인지, 누가 얼마나 아파하고 있는지, 그게 돈이 되는 구조인지 아닌지. 이건 사람이 판단해야 한다.

[![](https://substackcdn.com/image/fetch/$s_!-vBq!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4d010a82-46df-46e0-9502-a5b572d42a8b_512x512.jpeg)](https://substackcdn.com/image/fetch/$s_!-vBq!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F4d010a82-46df-46e0-9502-a5b572d42a8b_512x512.jpeg)

한국은 문제를 잘 푸는 데 최적화된 사회다. 교육 시스템 자체가 그렇다. 수능이라는 게 결국 주어진 문제를 정해진 시간 안에 정확하게 푸는 훈련이다. “이게 왜 문제인가”를 질문하는 연습은 12년 내내 한 번도 하지 않는다.

이 구조에서 세계 최고의 문제 풀이 능력이 나왔다. 그리고 바로 그 구조가, AI 시대에는 가장 큰 약점이 된다.

**비효율이라는 이름의 훈련소**

“무슨 문제를 풀 것인가”라는 고민은 어디서 오는가. 경험이다. 많이 겪고, 많이 느끼고, 많이 부딪혀봐야 한다.

좀 더 건조하게 말하면, 우리가 흔히 “비효율적”이라고 부르는 삶을 살아봐야 가능하다. 뭔가를 만들어서 빨리 돈을 벌겠다는 방향의 반대쪽으로 걸어봐야 한다. 목적 없이 돌아다녀보고, 엉뚱한 산업의 사람을 만나보고, 수지타산이 안 맞는 일을 해봐야 한다. 거기서 “어, 이건 왜 이렇게 되어 있지?”라는 질문이 나온다.

[![](https://substackcdn.com/image/fetch/$s_!LivC!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F15710a0d-f9c4-4c9b-a29d-a69df113d8ca_910x512.jpeg)](https://substackcdn.com/image/fetch/$s_!LivC!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F15710a0d-f9c4-4c9b-a29d-a69df113d8ca_910x512.jpeg)

같은 불편을 겪어도 “짜증나네” 하고 넘기는 사람과 “이거 왜 이렇지?”라고 멈추는 사람이 있다. 그 차이가 곧 문제 발견 능력이다. 그리고 그 능력은 여유에서 나온다.

한국 사회는 구조적으로 이 여유를 허락하지 않는다. 초등학교 때부터 학원을 돌리고, 대학 가서도 학점과 스펙을 쌓고, 취업하면 야근에 치인다. 비효율적으로 보이는 모든 것을 잘라내도록 설계된 사회다. 쓸데없는 시간을 보내는 것에 대한 죄책감이 DNA처럼 박혀 있다.

그 결과, 문제를 푸는 속도는 세계 1등인데 풀 만한 문제를 찾는 능력은 바닥이다.

**“뭘 만들지”가 아니라 “뭐가 아픈지”**

AI 툴은 계속 좋아질 것이다. 1년 뒤에는 지금보다 훨씬 강력한 도구가 나올 것이고, 누구나 더 복잡한 것을 만들 수 있게 될 것이다.

그때도 여전히 “뭘 만들지?”로 시작하는 사람과 “뭐가 불편하지?”로 시작하는 사람의 격차는 벌어진다. 오히려 도구가 강력해질수록 그 격차는 더 커진다. 실행력의 차이는 AI가 평준화시키지만, 문제 선택의 차이는 평준화되지 않는다.

[![](https://substackcdn.com/image/fetch/$s_!r9mT!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd1083e51-ab7d-48f7-a67f-ce8a0d3c3312_318x159.jpeg)](https://substackcdn.com/image/fetch/$s_!r9mT!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd1083e51-ab7d-48f7-a67f-ce8a0d3c3312_318x159.jpeg)

다음번 흑백개발자 해커톤이 열릴 때, 심사 기준이 “1주일 매출”이 아니라 “얼마나 깊은 문제를 건드렸는가”가 된다면 어떨까. 아마 나오는 결과물의 수준이 완전히 달라질 것이다. 문제는 그런 기준을 설정하는 것 자체가 한국에서는 어렵다는 점이다. 깊은 문제를 평가하려면 평가자도 그 깊이를 알아야 하니까.

한국의 AI 활용 속도는 진심으로 인상적이다. 그런데 속도는 방향이 맞을 때만 자산이다. 방향이 틀리면 빠를수록 더 엉뚱한데로 멀리 간다.

지금 한국에 필요한 건 더 좋은 AI 툴이 아니라 더 좋은 질문이다.`,
  },

  {
    title: "The World Google Is Dreaming Of",
    titleKo: "Google이 꿈꾸는 세계",
    excerpt: "구글이 현지 시간으로 금요일 밤 / 토요일 새벽 구글맵스의 새로운 버젼을 공개했다.",
    date: "Mar 14, 2026",
    category: "AI Investing",
    readTime: "4 min",
    canonicalUrl: "https://ethancho12.substack.com/p/google",
    slug: "world-google-is-dreaming-of",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "world", "dreaming", "google"],
    wordCount: 775,
    rating: 3,
    content: `구글이 현지 시간으로 금요일 밤 / 토요일 새벽 구글맵스의 새로운 버젼을 공개했다.

다소 짧은 영상이지만 몇 가지가 확실하게 눈에 띈다.

* 도심 내에서의 건물의 크기와 위치가 이미 모두 매핑이 되어 있다
* 미국 특유의 혼잡한 도로 시스템 속에서 몇차로를 이용해야 하는지 명확하게 보여준다
* 다리 밑을 통과하는지의 여부 등도 보여줘서 입체적인 공간을 이미 정밀하게 인지하고 있다

1차적인 해석은, 자율주행을 위한 진일보다.

2026년 Sundar와 재계약을 하면서 Waymo(자율주행)와 Wing(드론 딜리버리)에 페이의 상당 부분을 엮었다고 하더니, 바로 이런 feature가 발표된 건 우연인지, 필연인지, 여하튼 재미있는 타이밍이다.

[![](https://substackcdn.com/image/fetch/$s_!EfJi!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ffd4702d7-610a-4f3a-a90e-875d7222899b_1080x1350.jpeg)](https://substackcdn.com/image/fetch/$s_!EfJi!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ffd4702d7-610a-4f3a-a90e-875d7222899b_1080x1350.jpeg)

그런데 이 발표 전에 Google Maps가 다른 발표를 하나 먼저 했다. Ask Maps라는 제목으로 Gemini를 Google Maps에 이식시켜버린 것이다.

컨텍스트를 포함한 긴 문장을 Google Maps 에서 하면 동선과 일정까지 같이 짜주는 솔루션이다.

여기에서 다음 스텝은 쉽게 예상이 된다. Google의 가장 강력한 툴은 사실 Gmail과 Google Calendar이다. 이메일로 주고 받는 대화 속에서 Google은 얼마든지 향후 단기간 내에 사용자가 뭘 계획하고 있는지 알아낼 수 있다. Calendar로 보이는 사용자의 일정은 그야말로 빼박 증거이다. 물론 사용자의 동의를 받아야 할 테고 적법한 절차를 거쳐야 하겠지만, 사용자의 대리인, 그야말로 Agent의 역할을 가장 강력하게 lock-in 해서 음식점 예약, 미용실 예약, 물품 구입까지 일사천리로 진행될 것은 아주 쉽게 예상되는 바이다.

여기에서 내가 좀 아쉬운 부분은, 우리나라의 Naver와 Kakao도 사실 이에 못지 않은 데이터를 가지고 있다는 점이다. 물론 Calendar를 제대로 구현하지 못한 건 다양한 이유가 있기도 하고 아쉽기도 하지만, 네이버 카카오는 분명히 한국인들의 일정을 훨씬 더 잘 알고 있다.

[![](https://substackcdn.com/image/fetch/$s_!-iR-!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F11074a31-57af-4dfe-b54d-4df3cb72f14e_752x838.png)](https://substackcdn.com/image/fetch/$s_!-iR-!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F11074a31-57af-4dfe-b54d-4df3cb72f14e_752x838.png)

네이버 예약은 수많은 사람들이 활용하고 있고, 카카오톡에 들어 있는 수많은 개인들 간의 대화는 그야말로 정보의 보고이다. 실제 민감한 개인정보까지 들어가지 않더라도 이미 카카오도 카카오 선물하기로 원래 예상했던 것보다 훨씬 더 큰 사업을 성공적으로 만들어가고 있지 않은가?

[![](https://substackcdn.com/image/fetch/$s_!zU08!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fca603119-a2f2-4981-b019-4c8ef61de6a6_2542x1594.png)](https://substackcdn.com/image/fetch/$s_!zU08!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fca603119-a2f2-4981-b019-4c8ef61de6a6_2542x1594.png)

그런데 왜 거기까지일까?

그게 아쉽다.

내 개인적인 해석은, 여전히 충분히 큰 생태계를 보지 못하고 있어서이다. 이유가 어찌됐든 많은 한국 회사들은 스타트업들을 인수하는 데에 매우 인색하다. 그래서 발전이 더디다. 새로운 방향성을 잘 포용하지 못한다. 그래서 새로운 시도를 하는 것에도 굉장히 반발심이 강한 회사들이 많다.

Google Maps가 여기까지 오게 된 히스토리는 다음과 같다.

1. 서비스의 기초를 만든 핵심 인수

* **Where 2 Technologies (2004년):** 구글 맵스의 **탄생**. 원래 데스크톱용 프로그램이었던 기술을 구글이 인수해 웹 기반의 서비스로 전환시킴.
* **Keyhole (2004년):** 디지털 지구본 기술을 가진 회사로, 오늘날의 구글 어스(Google Earth)가 되었으며, 이번에 발표된 **3D 몰입형 뷰**의 원천 기술임.
* **ZipDash (2004년):** 당시로선 혁신적이었던 **실시간 교통 정보** 분석 기술을 제공.

2. ‘Ask Maps’와 커뮤니티 정보의 핵심: Waze

* **Waze (2013년):** 약 10억 달러에 인수된 이스라엘 스타트업.
* **영향:** 사용자들이 실시간으로 사고, 경찰 단속, 정체 구간을 보고하는 **크라우드 소싱** 데이터가 구글 맵스에 통합됨. 이번 업데이트에서도 구글은 “Maps와 Waze의 커뮤니티 데이터를 통합해 실시간 정보를 더 정확히 제공한다”고 명시. Ask Maps가 “지금 거기 사고 났어?” 같은 질문에 답할 수 있는 것도 Waze의 유산.

3. 디자인과 시각 정보의 진화

* **Urban Engines (2016년):** 도시 내 교통 흐름과 대중교통 데이터를 시각화하는 기술을 가짐. 지도가 단순한 그림을 넘어 ‘데이터의 시각화’로 변모.

  [![](https://substackcdn.com/image/fetch/$s_!fs-f!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd6f7a4f0-ded1-463b-8551-ac52bb4825ce_1200x675.webp)](https://substackcdn.com/image/fetch/$s_!fs-f!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd6f7a4f0-ded1-463b-8551-ac52bb4825ce_1200x675.webp)

이 다음 단계의 Google의 스텝 또한 매우 명확히 보인다. 분명히 Real World AI를 실현하기 위한 행보를 계속할 것이고, 그것을 위한 인수 작업 또한 이어질 것이 불보듯 뻔하다.

한국 IT 회사들도 반드시 이 방향으로 나아가야만 한다. 내부 R&D 좋다. 그런데 그것에만 매달리기에는 너무 늦다. 실패를 하더라도 진취적으로 M&A를 해야만 한다. 필요하다면 국내, 해외 스타트업 가리지 말고 인수를 해서 빠르게 치고 나가야 한다.

그야말로 광폭 행보를 빅테크들이 보이고 있다.

이미 추격해야 하는 거리가 꽤 멀다. 그런데 보폭 자체의 차이도 점점 커지고 있다.`,
  },

  {
    title: "Why we invested in a rice company",
    excerpt: "Most people have heard that rice contains heavy metals. Most people don’t think about it twice — until they’re feeding an infant.",
    date: "Mar 10, 2026",
    category: "AI Investing",
    readTime: "3 min",
    canonicalUrl: "https://ethancho12.substack.com/p/why-we-invested-in-a-rice-company",
    slug: "why-we-invested-in-a-rice-company",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "company", "invested"],
    wordCount: 674,
    rating: 3,
    content: `Most people have heard that rice contains heavy metals. Most people don’t think about it twice — until they’re feeding an infant.

[![](https://substackcdn.com/image/fetch/$s_!-nVu!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd62623d3-3b10-4416-8308-e3935b41c5bd_800x533.webp)](https://substackcdn.com/image/fetch/$s_!-nVu!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fd62623d3-3b10-4416-8308-e3935b41c5bd_800x533.webp)

Heavy metal contamination in baby food is not a new discovery. The U.S. congressional investigation in 2021 found detectable levels of arsenic, lead, and cadmium in products from major brands. Rice-based cereals were among the worst offenders. Rice absorbs heavy metals at a significantly higher rate than other grains. The science has been settled for years. What was missing was someone willing to engineer their way out of the problem at the production level.

**The Problem Is Structural, Not Incidental**

Contamination levels in baby food are largely a function of sourcing and processing decisions. Most manufacturers optimized for cost and shelf life. The heavy metal issue was treated as a regulatory compliance problem, not a product quality problem. That framing produces very different solutions.

[![](https://substackcdn.com/image/fetch/$s_!u9EA!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F36bd970a-06e7-4f48-8742-c49ed1195f6b_1952x1444.png)](https://substackcdn.com/image/fetch/$s_!u9EA!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F36bd970a-06e7-4f48-8742-c49ed1195f6b_1952x1444.png)

Duri Company reframed it as a supply chain problem. They source exclusively from certified organic Korean rice, which carries some of the lowest baseline arsenic levels in the world. Then they went further: a standardized washing and milling process that reduces heavy metal content by up to 74%. That number did not come from a lab study. It came from their own production line.

**What Made the Decision Easy**

I met Subin Heo, Duri’s founder, through our deal flow process. Her background is unconventional for a food startup — quantitative finance on Wall Street. What she brought to the table was a systems-level understanding of how to build a defensible product, not just a better label.

[![](https://substackcdn.com/image/fetch/$s_!OScD!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ffb1060f0-1142-4384-bde7-c93e813a056c_745x171.jpeg)](https://substackcdn.com/image/fetch/$s_!OScD!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Ffb1060f0-1142-4384-bde7-c93e813a056c_745x171.jpeg)

The early signals were clear. Within two months of launch, Duri had sold out its entire U.S. export allocation. FDA certification was in place. English-language packaging was ready. B2B distribution infrastructure was already being built. This was not a team preparing to enter the U.S. market. This was a team already inside it.

**Why the Market Opportunity Is Real**

The North American baby food market is approximately $9 billion. The premium and organic segment has grown consistently. But the heavy metal safety category is essentially unoccupied. Parents who are actively avoiding rice-based cereals because of contamination concerns have no credible alternative that combines safety credentials with product quality. That is the gap Duri is filling.

**The Bet**

Safe food has permanent demand. In the infant category, safety outranks price. The parent who reads the congressional report on heavy metals in baby food does not go back to the old brand because it is cheaper.

Duri Company is building the category that should have existed a decade ago. We invested at seed because the team had already done what most teams only plan to do.

That is the only kind of early-stage bet worth making.

---

*Ethan Cho is CIO and Partner at TheVentures, a Seoul-based early-stage venture firm. He writes about investment patterns at the intersection of Korean innovation and global markets.*`,
  },

  {
    title: "[Korean] You're Fired. Kind of.",
    titleKo: "You're Fired. Kind of.",
    excerpt: "2월 27일 오후 5시 1분, 미국 정부는 Anthropic을 “공급망 안보 위협”으로 지정했다. 트럼프는 전 연방기관에 Claude 사용 즉시 중단을 명령했다. 같은 날 밤 OpenAI가 펜타곤과 계약서에 서명했다.",
    date: "Mar 1, 2026",
    category: "AI Investing",
    readTime: "5 min",
    canonicalUrl: "https://ethancho12.substack.com/p/youre-fired-kind-of",
    slug: "youre-fired-kind-of",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "you're", "fired"],
    wordCount: 1078,
    rating: 3,
    content: `2월 27일 오후 5시 1분, 미국 정부는 Anthropic을 “공급망 안보 위협”으로 지정했다. 트럼프는 전 연방기관에 Claude 사용 즉시 중단을 명령했다. 같은 날 밤 OpenAI가 펜타곤과 계약서에 서명했다.

19시간 후 이란 공격이 시작됐다.

WSJ은 보도했다. 그 작전에서 CENTCOM이 사용한 AI는 Claude였다고.

[![](https://substackcdn.com/image/fetch/$s_!n1qH!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Faac740bb-4091-4f15-ba94-e6eaf9fe9c81_1264x1638.heic)](https://substackcdn.com/image/fetch/$s_!n1qH!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Faac740bb-4091-4f15-ba94-e6eaf9fe9c81_1264x1638.heic)

---

## 이 모순이 많은 것을 설명한다

정리하면 이렇다.   
1) Anthropic이 자율 살상 무기와 대규모 감시 사용을 거부했다.   
2) 펜타곤은 계약을 파기했다.   
3) OpenAI를 대안으로 서명했다.   
4) 그리고 실전에서는 쫓아낸 Claude를 썼다.

“너는 마음에 안 들어서 내보낸다”고 선언하면서 “근데 전쟁에서는 네가 필요하다”는 구조다.

[![](https://substackcdn.com/image/fetch/$s_!OwPo!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7c607c8d-f10f-4737-a949-a6e3fcf37328_860x484.heic)](https://substackcdn.com/image/fetch/$s_!OwPo!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F7c607c8d-f10f-4737-a949-a6e3fcf37328_860x484.heic)

이 모순이 드러내는 건 세 가지다.

첫째, 이 교체는 처음부터 실제 교체가 목적이 아니었다. OpenAI 서명은 Anthropic을 압박하기 위한 협상 카드로 활용하려 했었거나, 교체를 원했지만 당장 기술적으로 불가능하다는 현실을 스스로 드러낸 것이다.

둘째, Claude가 군사 시스템에 이미 너무 깊이 통합돼 있어서 “금지”를 선언해도 뺄 수가 없었다. 아무도 그 결정을 내리지 않은 사이, AI가 국가 폭력 인프라의 기본값이 됐다. Operation Epic Fury는 그 사실이 처음으로 공개된 순간이다.

셋째, Anthropic 입장에서는 역설적으로 자신들의 가치가 증명됐다. 쫓아내겠다고 협박해도 실전에서는 결국 자기 것을 썼으니까.

---

## Claude가 그 자리에 있게 된 이유

Anthropic은 2024년 말 Palantir를 통해 펜타곤 계약을 맺었다. 분류 네트워크에 접근한 최초의 AI 기업이었다. 이후 1월 마두로 체포 작전에서 처음 실전 투입됐다. 정보 분석, 타겟 식별 지원, 전투 시나리오 시뮬레이션. 그 결과가 검증됐기 때문에 이란 작전에서도 그대로 썼다.

군이 원하는 건 윤리적으로 올바른 AI가 아니다. 실전에서 작동하는 AI다. Claude는 두 번의 실전 데이터가 쌓인 유일한 AI였다.

OpenAI가 계약서에 서명한다고 내일부터 같은 성능을 분류 환경에서 낼 수 있는 게 아니다.

---

## 그럼 진짜 교체가 일어나는가

6개월이 관건이다. 계약상 전환 기간이 6개월이다. 이 기간 동안 OpenAI와 xAI가 분류 네트워크에서 충분히 검증되면 교체는 일어난다.

하지만 두 가지 변수가 있다.

하나는 이란 전쟁의 장기화다. 전쟁이 계속되면 작전 연속성이 중요해진다. 검증된 시스템을 교체하는 건 리스크다. 현장 지휘관은 새 AI를 실전에 처음 투입하고 싶지 않다.

다른 하나는 성능 차이다. 6개월 후 OpenAI 시스템이 분류 환경에서 Claude와 같은 수준이라고 검증되면 교체가 완성된다. 그렇지 않으면 “사실상 두 시스템 병행” 구조가 된다. 그리고 그 상태가 지속되면, 트럼프 행정부가 Anthropic에게 조용히 다시 손을 내밀 가능성도 있다.

다만 그때는 협상 레버리지가 Anthropic 쪽에 없다. 한 번 “공급망 위협” 낙인을 받은 상태에서 돌아오는 것과 처음부터 협상하는 것은 다르다.

---

## Anthropic이 거부한 것의 본질

Amodei가 1월에 쓴 문장이 있다. “한 명 혹은 소수의 사람이 드론 군대를 다른 인간의 협조 없이 작동시킬 수 있는 구조를 가장 두려워한다.”

[![](https://substackcdn.com/image/fetch/$s_!P0W5!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fcc8195d1-082a-4c8c-8e93-e4e0f6624619_1166x1770.heic)](https://substackcdn.com/image/fetch/$s_!P0W5!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fcc8195d1-082a-4c8c-8e93-e4e0f6624619_1166x1770.heic)

이게 핵심이다. 윤리나 책임 문제가 아니다. 폭력의 마찰이 사라지는 것에 대한 두려움이다.

대규모 폭력에는 원래 마찰이 있었다. 전쟁을 일으키려면 수천 명의 군인을 동원해야 하고, 지휘 체계를 설득해야 하고, 물자 보급을 조직해야 한다. 각 단계마다 인간이 협조해야 한다. 그 마찰이 사실상 견제 장치였다. 독재자도 혼자 전쟁을 일으킬 수 없었다. 사람들을 움직여야 했으니까.

완전 자율 AI 무기는 그 마찰을 없앤다. 소수가 대규모 폭력을 인간 협조 없이 실행할 수 있게 된다. 의회가 검토하기 전에, 언론이 보도하기 전에, 여론이 형성되기 전에 일이 끝난다. 민주적 견제가 작동할 시간 자체가 없어진다.

Anthropic은 그 구조의 부품이 되기를 거부했다. 이란 공격 개시 결정은 새벽 2시 30분 트럼프의 Truth Social 영상 메시지로 세상에 알려졌다. 의회 승인 없었다. 사전 공개 토론 없었다. 인간의 마찰이 최소화된 전쟁이었다.

---

## OpenAI는 그냥 굴복한 건가

이 지점에서 OpenAI를 단순히 “굴복”으로 보면 사태를 오독하게 된다.

Sam Altman은 계약 후 공개 성명을 냈다. “우리도 자율 살상 무기와 대규모 감시는 금지한다.” 그리고 Anthropic의 블랙리스트 지정을 “매우 나쁜 결정”, “극도로 무서운 선례”라고 공개 비판했다. 경쟁사를 편든 것이다.

[![](https://substackcdn.com/image/fetch/$s_!mqPQ!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F51641d30-21fb-4cea-a316-751ce6287ce3_1202x966.heic)](https://substackcdn.com/image/fetch/$s_!mqPQ!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F51641d30-21fb-4cea-a316-751ce6287ce3_1202x966.heic)

차이는 구조였다. Anthropic은 Palantir를 통해 군 분류 네트워크에 직접 통합됐다. OpenAI는 클라우드 배포만 허용했다. 얼핏 보면 OpenAI가 더 신중한 것처럼 보인다. 하지만 반대다. 클라우드 너머 현장에서 자사 모델이 어떻게 쓰이는지 OpenAI는 볼 수 없다. 레드라인을 계약서에 아무리 잘 써놔도, 그 선이 지켜지는지 확인할 가시성이 없다. 더 깊이 들어갔던 쪽이 거부했고, 덜 들어간 쪽이 동의했다. Altman 본인도 이 딜이 “서둘렀고 optics가 좋지 않다”고 인정했다.

---

## 시장은 다른 판단을 내렸다

같은 날, Claude는 미국 앱스토어 1위를 찍었다. 1월 말 42위에서 한 달 만에 정상이다. ChatGPT가 2위로 밀렸다. 앱스토어 1~3위를 Claude, ChatGPT, Gemini가 동시에 점령한 것도 처음이다.

Anthropic이 공개한 수치를 보면, 올해 유료 구독자 2배 증가, 무료 유저 60% 증가, 일일 신규 가입 한 주 연속 역대 최고 기록.

정부가 “너는 위험하다”고 낙인찍은 순간, 소비자들은 반대로 움직였다.

심지어 무려 Katy Perry가 Claude 유료 구독을 인증하는 기염을 토했다.

[![](https://substackcdn.com/image/fetch/$s_!mQdO!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F6af86d40-d87c-4b24-865b-43fbfbbcfee4_640x756.heic)](https://substackcdn.com/image/fetch/$s_!mQdO!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F6af86d40-d87c-4b24-865b-43fbfbbcfee4_640x756.heic)

이게 지속될지는 모른다. 관심이 전환으로 이어지는지는 다음 분기 수치가 말해줄 것이다. 하지만 한 가지는 확실해졌다. AI 안전성이 소비자 선택의 실제 기준이 될 수 있다는 것. 정부의 탄압이 브랜드 자산이 될 수 있다는 것.

트럼프의 제재가 세상에서 가장 비싼 PR이 됐다.

---

## 이 이야기가 끝나지 않은 이유

이란 전쟁은 진행 중이다. 이란의 반격이 계속되고 있고, 두바이와 아부다비 공항이 피격됐다. 전쟁이 어디까지 가는지는 아무도 모른다.

그 전쟁에서 타겟을 식별하는 데 쓰인 AI의 회사는 지금 정부에서 쫓겨난 상태다.   
그 AI는 쫓겨난 이후에도 실전에서 계속 돌아가고 있다.   
그리고 소비자들은 그 회사의 앱을 역대 가장 빠른 속도로 다운로드하고 있다.

이 세 가지가 동시에 일어나고 있다는 게, 우리가 지금 어떤 시대에 진입하고 있는지를 보여준다.

정신이 하나도 없다.`,
  },

  {
    title: "Your Boss Will Hate This Post",
    titleKo: "사장님이 이 글을 싫어합니다",
    excerpt: "크게 두 가지로 나눠질 것이다.",
    date: "Feb 20, 2026",
    category: "Operator Insights",
    readTime: "4 min",
    canonicalUrl: "https://ethancho12.substack.com/p/0fe",
    slug: "your-boss-will-hate-this-post",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle"],
    wordCount: 814,
    rating: 3,
    content: `크게 두 가지로 나눠질 것이다.

1) 오예, 그럼 8시간이면 원래 32시간 걸리던 일이 가능해지겠네 (사장님과 몇몇 임원들)

2) 오예, 얼른 끝내고 6시간 동안 놀아야지 (그 외 모두)

둘 다 행복할 것이다. 그런데 둘 중 하나만 현실이 될 것이다.

아마존은 지금 이 질문에 공식 답변을 내놓고 있다. 두 가지 숫자를 동시에 추적하는 방식으로.

하나는 직원이 AI 툴을 얼마나 쓰는가. 내부 시스템 ‘Clarity’가 어떤 AI를 얼마나 활용했는지 기록하고, 이게 인사평가와 승진에 반영된다.

다른 하나는 직원이 사무실에 얼마나 오래 앉아 있는가. 지난 12월부터 관리자 대시보드가 배포됐다. 8주 평균 하루 4시간 미만이면 ‘Low-Time Badger’, 한 번도 출근 안 하면 ‘Zero Badger’로 찍힌다.

얼핏 보면 마이크로 매니지먼트처럼 보인다. 실제로는 그보다 더 심각하다. 이 두 지표는 방향이 반대이기 때문이다.

---

**AI를 잘 쓸수록 사무실에 오래 있을 이유가 없다**

지식노동에서 AI의 효과는 단순하다. 같은 품질의 결과물을 더 빨리 만든다. 보고서 초안을 4시간에서 40분으로 줄이고, 데이터 분석을 반나절에서 1시간으로 압축한다. AI를 잘 쓰는 직원일수록 유효 업무 밀도가 올라간다. 그리고 일찍 끝낸다.

[![](https://substackcdn.com/image/fetch/$s_!jVUm!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fbf07e07d-ae52-4057-a190-c94300f9e557_332x152.jpeg)](https://substackcdn.com/image/fetch/$s_!jVUm!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fbf07e07d-ae52-4057-a190-c94300f9e557_332x152.jpeg)

아마존의 두 지표를 동시에 만족시키려면 이렇게 해야 한다. AI로 2시간 만에 8시간 어치 일을 끝내고, 남은 6시간 동안 24시간 어치를 추가로 해내면 된다. 아마존이 원하는 건 효율화가 아니라 효율화로 생긴 여백을 다시 착취하는 것이다. 이게 아마존이 원하는 ‘혁신적이고 효율적인 직원’의 모습인가.

이 모순은 우연이 아니다. 두 지표가 추구하는 것이 애초에 다르다.

---

**AI 추적은 효율을 원하고, 출근 추적은 통제를 원한다**

아마존이 AI 사용량을 측정하는 이유는 분명하다. 최근 3개월간 3만 명을 해고했다. 30년 역사상 최대 규모다. 남은 직원들이 AI로 그 빈자리를 메우길 원한다. 효율화의 과실을 직원이 아닌 회사가 가져가는 구조다.

[![](https://substackcdn.com/image/fetch/$s_!QYQJ!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5744a81b-6370-426d-881c-ab0a21f0d0db_1464x1022.png)](https://substackcdn.com/image/fetch/$s_!QYQJ!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F5744a81b-6370-426d-881c-ab0a21f0d0db_1464x1022.png)

출근 추적은 다른 논리다. 이건 AI 시대의 발명품이 아니라 산업화 시대의 유산이다. 공장에서 시작됐다. 몸이 라인 앞에 있어야 물건이 나오니까. 지식노동에 그대로 이식됐고, 측정이 어려우니 ‘일단 앉아 있으면 일하는 것’으로 대충 대체됐다.

팬데믹이 이 등식을 흔들었다. 재택근무를 해도 일이 됐다. 그러자 경영진이 불편해졌다. 눈에 보이지 않는 직원을 신뢰하는 게 어려웠고, 수조 원짜리 부동산을 정당화해야 했고, ‘문화’라는 이름으로 통제권을 되찾고 싶었다. RTO는 효율의 언어를 빌렸지만, 본질은 권력의 문제다.

---

**측정하는 것이 관리하는 것이 된다**

아마존 직원들은 지금 두 개의 게임을 동시에 하고 있다. AI를 얼마나 썼는지 기록을 남기는 게임, 그리고 사무실에 얼마나 오래 앉아 있었는지 수치를 채우는 게임. 실제로 좋은 일을 했는가는 두 번째 질문이 됐다.

[![](https://substackcdn.com/image/fetch/$s_!MwSe!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F10ba948d-5d94-4d5d-aa83-18f28086e3be_500x500.jpeg)](https://substackcdn.com/image/fetch/$s_!MwSe!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F10ba948d-5d94-4d5d-aa83-18f28086e3be_500x500.jpeg)

측정 시스템이 행동을 만들어낸다. 직원들은 측정되는 것에 최적화한다. AI를 진짜 창의적으로 쓰는 게 아니라 ‘Clarity’에 기록이 남도록 쓰고, 사무실에 일하러 오는 게 아니라 대시보드 수치를 채우러 온다.

조직이 측정하는 것과 조직이 원하는 것이 다를 때, 직원들은 전자를 선택한다. 항상.

그렇다면 “최선을 다하라”는 말은 아직 유효한가. 이 말이 전제하는 건 최선의 총량이 고정돼 있다는 것이다. 8시간 동안 죽어라 집중하면 그게 최선이라는 산업화 시대의 논리다. AI 시대엔 이 전제가 무너진다. 2시간에 8시간 어치를 해내는 사람한테 “더 최선을 다하라”는 말은 뭘 의미하는가. 더 오래 앉아 있으라는 건가, 아니면 더 좋은 프롬프트를 쓰라는 건가.

2시간에 8시간 어치의 일이 가능해진 순간, 남은 6시간을 두고 두 개의 시선이 엇갈린다. 직원은 그 시간이 자기 것이라고 생각한다. 4시간짜리 일이 1시간으로 줄었으니 남은 3시간은 내가 번 것이다. 회사는 반대로 읽는다. 4배 빨라졌으면 4배 더 해라. 1시간짜리가 된 일을 16번 시켜서 하루를 꽉 채운다. 같은 효율화를 보고 한쪽은 3을 얻었다고 생각하고, 다른 쪽은 16을 요구한다. 아마존의 두 지표는 이 충돌의 공식 선언이다.

시간이라는 축 자체가 무너지고 있다. OpenClaw를 써본 사람은 안다. 한 시간 걸릴 거라 생각하고 맡겼더니 5분 후에 끝났다고 돌아온다. 이 경험을 한 번이라도 해본 사람한테 “사무실에 4시간 앉아 있어라”는 말이 무슨 의미인가.

---

**진짜 질문은 따로 있다**

아마존의 이 실험은 전 산업의 문제를 압축해서 보여준다.

AI 도입을 외치는 기업들의 측정 시스템은 아직 산업화 시대에 머물러 있다. 출근 일수, 회의 참석률, 보고서 제출 횟수. AI 시대에 맞는 생산성 측정 방식은 아직 존재하지 않는다. 시간이 아닌 임팩트, 출석이 아닌 의사결정의 질, 보고서 수가 아닌 문제 해결력. 이걸 어떻게 객관적으로 측정할 것인가. 이 질문에 답을 낸 조직이 AI 시대의 진짜 승자가 된다.

아마존은 지금 그 답을 찾지 못한 채로 두 개의 낡은 지표를 동시에 돌리고 있다. 세계 매출 1위 기업이 아직도 이 문제를 못 풀었다는 건, 역설적으로 이 문제가 얼마나 어려운지를 보여준다.`,
  },

  {
    title: "Anger Is Not Free",
    titleKo: "분노는 공짜가 아니다",
    excerpt: "국회의원들은 카메라 앞에서 분노했다. 그 분노가 미국 로펌의 손에 들어갔다.",
    date: "Feb 18, 2026",
    category: "Operator Insights",
    readTime: "1 min",
    canonicalUrl: "https://ethancho12.substack.com/p/dfe",
    slug: "anger-is-not-free",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "anger"],
    wordCount: 89,
    rating: 3,
    content: `국회의원들은 카메라 앞에서 분노했다. 그 분노가 미국 로펌의 손에 들어갔다.

쿠팡 개인정보 유출 사태는 3,370만 명, 대한민국 인구 65퍼센트의 데이터가 노출된 심각한 사건이다. 기업은 당연히 책임을 져야 한다.

하지만 이번 에피소드에서 주목해야 할 건 다른 지점이다. 청문회에서 여야를 가릴 것 없이 쏟아낸 “한국을 떠나라”, “영업정지를 검토하겠다”는 발언들이, ISDS 신청서에 차별적 규제의 증거로 그대로 실렸다. 소리는 국회에서 질렀는데, 청구서는 외교부와 산자부 협상 테이블에 날아왔다. 자기들은 영웅 행세를 했고, 뒷수습은 완전히 다른 사람들의 몫이 됐다.

처벌과 정치 쇼는 다르다. 그리고 그 차이의 대가는, 결국 국민이 치른다.

분노는 공짜가 아니다.`,
  },

  {
    title: "The 20-Watt Genius and the 1000-Watt Fool",
    titleKo: "20와트의 천재, 1000와트의 바보",
    excerpt: "설이다. 민족의 대이동이 시작된다.",
    date: "Feb 16, 2026",
    category: "Decision Frameworks",
    readTime: "5 min",
    canonicalUrl: "https://ethancho12.substack.com/p/20-1000",
    slug: "20-watt-genius-1000-watt-fool",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "genius"],
    wordCount: 982,
    rating: 3,
    content: `설이다. 민족의 대이동이 시작된다.

서울에서 부산까지 4시간. 설 연휴에는 10시간이 되고, 12시간이 된다. 어렸을 때부터 수없이 경험했다. 그때마다 궁금했다. 이 끝없는 정체를 항공샷으로 찍으면 어떤 모습일까.

답은 이미 알려져 있다. 2008년 나고야 대학의 실험이 증명했다. 원형 트랙에 22대의 차량을 올려놓고 일정한 속도로 달리게 했다. 사고도 없고, 공사도 없고, 차선 축소도 없었다. 그런데 몇 바퀴 뒤, 단 한 명의 운전자가 미세하게 브레이크를 밟자, 그 감속이 뒤로 전파되면서 완전 정지 구간이 생겨났다. 유령 정체(phantom traffic jam).

병목의 원인은 도로가 아니다. 인간이다.

자, 한 가지만 상상해보자. 인간 운전자가 단 한 명도 없다면. 인간의 평균 반응 시간 1.5초가 AI의 밀리초로 대체되고, V2V 통신으로 군집 전체가 동시에 판단한다면. 브레이크 파동 자체가 사라진다. 유령 정체가 물리적으로 불가능해진다. 물리법칙과 타이어 마찰력만이 제약인 세상.

당신은 이 세상이 상상되는가. 솔직히 대부분은 못한다. “2시간? 1시간?” 정도를 떠올린다. 4시간이라는 기존 경험이 앵커(anchor)이기 때문이다. 앵커 자체가 무의미해지는 시나리오는, 말 그대로 상상의 바깥에 있다.

이 글은 고속도로 이야기가 아니다.

---

**병목은 인간이다.**

인간의 뇌는 약 20와트로 작동한다. LED 전구 하나의 전력이다. 체중의 2%에 불과하지만 전체 에너지의 20%를 가져간다. 뇌는 에너지를 비축하지 못하며, 혈액을 통해 실시간으로 공급받아야만 작동한다. Quanta Magazine이 보도한 Monash University의 연구에 따르면, 뇌가 집중적 사고를 할 때조차 휴식 대비 에너지 소비 증가는 겨우 5%다. 근육이 운동 시 3~4배를 쓰는 것과는 차원이 다르다. 이미 아이들링 상태에서 거의 전력을 쏟아붓고 있다는 뜻이다.

이 극한의 에너지 제약이 인간 지능의 두 가지 핵심 특성을 만들어냈다.

첫째, **Selective Ignorance — 전략적 무지.** 콜롬비아에서 네 번째로 큰 도시를 모르는 것은 기억의 실패가 아니다. 뇌가 불필요한 정보의 저장을 거부한 것이다. 20와트의 예산에서 “무엇을 무시할 것인가”가 지능의 핵심 기능이 된다.

둘째, **Satisficing — 충분히 괜찮은 해.** 노벨 경제학상 수상자 Herbert Simon이 만든 개념이다. 인간은 최적해를 찾지 않는다. 충분히 괜찮은 해를 가장 빠르게 찾는다. “귀찮다”는 것은 게으름이 아니라, 20와트 뇌의 에너지 효율 최적화가 설계대로 작동하는 것이다.

이 두 가지는 버그가 아니라 피처다. 그리고 이 피처 위에 문명이 지어졌다. Adam Smith의 분업은 “모든 사람이 모든 것을 알 수 없다”는 한계의 경제적 번역이다. 시장 가격 메커니즘은 분산된 정보를 집약하는 장치이며, 이것이 작동하는 이유는 어떤 개인도 모든 정보를 가질 수 없기 때문이다. 벤처캐피탈이 존재하는 이유도, 결국 정보 비대칭 — 대부분의 투자자가 좋은 스타트업을 알아보는 데 필요한 판단력을 갖추지 못한다는 전제 위에 서 있다. 분업, 전문화, 관료제, 대의 민주주의, 시장 경제 — 인류 문명의 핵심 제도들은 전부 20와트 뇌의 한계에 대한 적응이다.

그런데 인공지능은 selective ignorance와 satisficing을 더럽게 못한다. ChatGPT에 콜롬비아의 네 번째 도시를 물으면 즉시 답한다. 모든 것을 알고, 모든 것에 답한다. 에너지 제약이 없는 시스템의 당연한 귀결이다. 그래서 지금까지의 평가는 이랬다 — AI는 에너지 효율에서 인간에 비해 압도적으로 열등하다. 20와트로 세상을 해석하는 시스템과, 수천 와트로 텍스트를 생성하는 시스템. “AI는 별로”라는 결론이 나올 만도 하다.

하지만 이 프레임이 완전히 무너지는 순간이, 지금 오고 있다.

---

**게이트키퍼가 사라진다.**

지금까지 AI 논의는 “인간이 AI를 도구로 쓰는” 구조를 전제해왔다. 이 구조에서 인간의 20와트 뇌는 병목이다. 설 연휴 고속도로의 인간 운전자와 정확히 같다. 뭘 물어야 할지 모르면 못 물어본다. 100개의 경로 중 3개만 탐색하고 “이 정도면 됐지”라고 판단한다. AI의 잠재력은 인간의 인지적 한계만큼만 해제된다.

2025년, 그 병목이 제거되기 시작했다. Gartner에 따르면 멀티에이전트 시스템에 대한 문의가 1년 사이 1,445% 급증했다. Anthropic의 MCP(Model Context Protocol)가 업계 표준으로 자리잡았고, Google이 A2A(Agent-to-Agent Protocol)를 제시했다. HTTP가 모든 브라우저와 서버를 연결한 것처럼, 이 프로토콜들은 AI가 AI를 호출하고 조율하는 기반을 놓고 있다.

AI-on-AI. Orchestrator AI가 문제를 분해하고, 전문 Agent들이 모든 경로를 탐색하며, 결과를 다시 종합한다. 피로도 없고, 에너지 제약도 없고, “이 정도면 됐지”도 없다.

고속도로에서 인간 운전자를 제거하면 유령 정체가 사라지듯, AI 시스템에서 인간 병목을 제거하면 “점진적 개선”이 아니라 “차원 이동”이 일어난다. 인간이 AI를 쓸 때, 20와트 뇌는 1000와트 시스템의 게이트키퍼였다. AI가 AI를 쓸 때, 그 게이트키퍼가 사라진다.

---

**당신이 보지 못하는 것.**

사진과 8K 동영상, 그리고 정물화에서 느끼는 감동은 다르다. 렘브란트의 자화상이 숨을 멎게 하는 것은 정보가 많아서가 아니라, 무엇을 빼야 하는지를 알았기 때문이다. 감동은 데이터의 밀도가 아니라 빈칸의 설계에서 온다. 하이쿠의 17음절, 첫사랑의 기억에서 상대방 얼굴만 선명한 것, 설 연휴 할머니 집의 기억에서 된장찌개 냄새만 남아있는 것 — 전부 selective ignorance의 산물이다. 인간의 한계가 곧 인간의 아름다움이었다.

AI에게는 8K가 정물화보다 “좋다.” 더 많은 데이터, 더 많은 신호. AI가 AI의 출력을 소비할 때, 감동이라는 기준은 존재하지 않는다. 여백은 의미가 아니라 비효율이다. 무손실 완전성이 유일한 가치 기준이다.

바로 이 지점에서, AI 무용론과 버블론의 맹점이 드러난다.

“AI가 별로다.” “기대에 못 미친다.” “할루시네이션이 너무 많다.” 전부 맞다 — 인간의 평가 기준에서는. 그런데 AI-on-AI 루프가 닫히는 순간, 인간의 평가는 시스템의 변수에서 빠진다. 할루시네이션은 검증 에이전트가 밀리초 안에 교차 검증한다. 장황한 답변은 AI에게 오히려 신호 밀도다. 느린 속도란 인간의 체감 기준이며, AI-on-AI에서 1초는 수천 번의 상호작용이 가능한 시간이다.

마차를 타는 사람이 자동차를 평가했다. “시끄럽고, 냄새나고, 말보다 고장이 잦다.” 전부 맞았다 — 마차의 기준에서는. 하지만 자동차는 마차를 대체하려고 만들어진 것이 아니었다. 자동차가 자동차를 위한 인프라 — 고속도로, 주유소, 교외 주거지 — 를 만들어낸 뒤, 마차의 평가 기준 자체가 소멸했다.

지금 AI 회의론이 간과하는 것이 정확히 이것이다. AI의 궁극적 고객이 인간이라는 전제 위에서 “가성비가 안 나온다”고 말하고 있다. 그런데 AI의 궁극적 고객이 다른 AI가 되는 순간 — 그리고 그 순간이 지금 오고 있다 — 인간 기준의 가성비 계산은 의미를 잃는다. 그리고 1000와트를 돌릴 수 있는 것은 자본이다. AI-on-AI를 구축할 수 있는 소수의 Big Tech와, 여전히 20와트로 세상을 해석해야 하는 나머지 사이의 격차는, 재산의 불평등도 정보의 불평등도 아닌, 인지 능력 자체의 불평등이다.

---

**파도 앞에서.**

나는 20년 넘게 기술 산업과 벤처 투자에 몸담아왔다. 인터넷, 모바일, 클라우드 — 매번 과잉 흥분이 있었고, 매번 과소 평가가 있었다.

AI-on-AI에 대해서는, 과소 평가가 훨씬 위험하다.

과잉 흥분은 자기 교정된다. 투자가 앞서가면 시장이 조정한다. 하지만 과소 평가는 교정이 안 된다. 가만히 있으면 파도가 그냥 지나간다. 파도 위에 있는 사람은 올라가고, 해변에서 “별것 아니네”라고 말한 사람은 그 자리에 남는다.

“AI가 별로”라는 판단이 정밀한 분석의 결과인지, 20와트 뇌의 에너지 절약 모드인지를, 정직하게 물어야 한다.

설 연휴, 고속도로에 갇혀 있을 때 한번 생각해보시라. 이 정체의 원인이 도로가 아니라 인간이라는 것을. 그리고 지금 AI의 병목도, AI가 아니라 인간이라는 것을.

고속도로에서 인간을 빼면 유령 정체가 사라진다. AI에서 인간을 빼면, 우리가 아직 이름도 붙이지 못한 무언가가 시작된다.

우리는 아직 준비가 안 되어 있다. 그리고 이것이 과장이라고 느낀다면, 그 느낌이 분석인지 satisficing인지를 — 한 번만 더 생각해보시라.`,
  },

  {
    title: "Chains, Debt, Algorithms",
    titleKo: "쇠사슬, 부채, 알고리즘",
    excerpt: "오늘 글은 좀 어렵고, 무겁고, 복잡하다.",
    date: "Feb 15, 2026",
    category: "Market Analysis",
    readTime: "7 min",
    canonicalUrl: "https://ethancho12.substack.com/p/b0d",
    slug: "chains-debt-algorithms",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "chains", "algorithms"],
    wordCount: 1406,
    rating: 3,
    content: `오늘 글은 좀 어렵고, 무겁고, 복잡하다.

그런데 꼭 한 번 정리해보고 싶은 주제다.

---

### I. 자유를 선물 받은 사람들

1865년 1월, 미합중국 수정헌법 제13조가 비준되었다. 약 400만 명의 흑인 노예가 법적으로 자유인이 되었다. 역사책은 이 순간을 위대한 진보로 기록한다. 그리고 그 서사는 거기서 멈춘다.

그런데, 우리는 좀 더 들여다봐야 한다.

해방 직후 벌어진 일을 직시해야 한다. 400만 명이 하루아침에 “자유인”이 되었다. 그런데 이들에게는 토지가 없었다. 자본이 없었다. 문해력이 없었다. 사회적 네트워크가 없었다. 심지어 이들 대다수는 태어난 곳 이외의 지리를 알지 못했다. 이 상태에서 주어진 “자유”란 무엇이었나.

답은 간단하다. **껍데기였다.**

해방된 노예 대다수는 같은 농장에서 소작농(sharecropper)이 되었다. 더 이상 주인의 “재산”은 아니었지만, 주인의 땅에서, 주인의 종자를 빌려, 주인의 가격에 면화를 팔았다. 법적 신분은 바뀌었으나 경제적 종속 구조는 그대로였다. 쇠사슬이 사라진 자리에 부채(debt)가 들어앉았다. 채찍 대신 신용 시스템(credit system)이 사람을 묶었다.

이것이 역사가 보여주는 첫 번째 교훈이다.

**지배 시스템은 죽지 않는다.   
업그레이드된다.**

그리고 업그레이드의 가장 효과적인 방법은 “자유를 부여한다”는 서사를 입히는 것이다.

---

### II. 해방선언의 숨겨진 경제학

링컨을 도덕적 영웅으로만 읽는 것은 역사를 절반만 읽는 것이다.

노예해방선언(Emancipation Proclamation, 1863)의 맥락을 보라. 이 선언은 남북전쟁 와중에 발표되었다. 적용 범위는 “반란 중인 남부 주”에 국한되었다. 북부의 노예주(경계주)에는 적용되지 않았다. 군사 전략이자 외교 전략이었다. 영국과 프랑스가 남부를 승인하지 못하도록 도덕적 명분을 선점하는 한편, 남부 경제의 근간인 노예 노동력을 와해시키려는 전쟁 수단이었다.

이 사실이 링컨의 업적을 무효화하지는 않는다. 그러나 한 가지를 분명히 한다. **“자유”의 부여에는 항상 부여하는 쪽의 경제적 계산이 내장되어 있다는 것이다.**

북부 산업자본에게 노예 해방은 도덕적 사업이 아니라 노동시장의 재편이었다. 남부의 봉건적 농업 경제를 해체하고, 400만 명의 새로운 임금 노동자를 산업 경제로 편입시키는 과정이었다. “자유로운 노동자”는 “소유된 노동자”보다 경제적으로 효율적이다. 임금을 주되, 주거와 의료와 노후의 비용은 노동자 본인에게 전가할 수 있기 때문이다.

해방은 시스템의 관점에서 보면 비용 구조의 최적화였다.

---

### III. 2025년의 해방선언

이제 160년을 건너뛰자.

2024-2025년, 전 세계 기술 산업이 하나의 서사에 수렴하고 있다. **“AI가 인간을 반복 노동에서 해방시킨다.”** 이것이 OpenAI의 서사이고, Google의 서사이고, Microsoft의 서사이다. 모든 AI 컨퍼런스의 키노트가 이 문장의 변주다.

이 서사의 구조를 링컨의 해방선언과 나란히 놓으면, 불편할 정도로 대칭적이다.

**1865년:** “더 이상 다른 인간의 소유물이 아니다. 자유롭게 일하고 살 수 있다.”

**2025년:** “더 이상 반복 업무의 노예가 아니다. 창의적이고 인간적인 일에 집중할 수 있다.”

두 선언 모두 “해방”이라는 단어를 사용한다. 두 선언 모두 선언의 주체가 피선언자(해방되는 자)가 아니라는 공통점이 있다. 노예는 스스로 자신을 해방하지 않았다. 오늘날 사무직 노동자도 스스로 AI 전환을 선택한 것이 아니다. **해방은 위에서 내려온다. 항상.**

그리고 두 선언 모두, 선언의 이면에 선언자의 경제적 이해가 정확하게 내장되어 있다.

---

### IV. 새로운 소작제의 아키텍처

해방된 노예가 소작농이 되었듯, “AI로 해방된” 노동자는 어디로 가는가.

냉정하게 보자.

AI가 중간 숙련 업무(mid-skill tasks)를 대체하면, 그 자리에 있던 사람에게 두 가지 경로가 열린다. 위로 올라가거나, 아래로 내려가거나. “AI를 활용해 더 창의적인 일을 하라”는 것이 공식 서사다. 현실에서는 다수가 아래로 내려간다. 더 불안정한 긱 이코노미(gig economy)로, 더 파편화된 계약 노동으로.

그런데 여기서 구조를 자세히 봐야 한다.

AI 시대의 생산수단은 무엇인가. 데이터, 컴퓨팅 파워, 모델이다. 이 세 가지를 누가 소유하고 있는가. Nvidia가 GPU를 만들고, Microsoft/Google/Amazon이 클라우드를 운영하며, OpenAI/Anthropic/Google이 모델을 훈련시킨다. 개인 노동자는 이 인프라 위에서 월 $20의 구독료를 내고 “자유롭게” 일한다.

이 구조는 소작제(sharecropping)의 디지털 버전이 아닌가.

소작농은 지주의 땅에서, 지주의 종자로, 지주의 가격에 면화를 팔았다. 오늘의 지식 노동자는 빅테크의 클라우드에서, 빅테크의 모델로, 빅테크의 플랫폼 위에서 결과물을 생산한다. 토지 소유가 농업 경제의 권력이었듯, **인프라 소유가 AI 경제의 권력이다.** 그리고 그 인프라는 역사상 유례없이 소수의 손에 집중되어 있다.

소작농에게 “너는 자유인이다”라고 말한 것과, 월 $20 구독자에게 “AI가 당신을 자유롭게 한다”고 말하는 것 사이의 거리는 얼마나 되는가.

---

### V. 자유의 세 개의 층위

여기서 “자유”라는 개념 자체를 해부해야 한다. 자유에는 최소 세 개의 층위가 있다.

**첫째, 형식적 자유(Formal Freedom).** 법적 신분의 변경. 노예가 아닌 자유인. 누구나 AI 도구에 접근할 수 있다는 선언. 이것은 자유의 가장 얕은 층이다. 필요조건이지만 충분조건이 아니다. 형식적 자유만으로는 아무것도 바뀌지 않는다. 이것은 역사가 반복적으로 증명한 사실이다.

**둘째, 실질적 자유(Substantive Freedom).** 경제적 자립, 교육, 사회적 이동성. 토지도 자본도 문해력도 없이 풀려난 노예에게 형식적 자유는 공허했다. 마찬가지로, AI 리터러시도, 데이터도, 컴퓨팅 자원도, 영어 능력도 없는 개인이나 국가에게 “AI 민주화”는 실리콘밸리의 마케팅 용어일 뿐이다. 실질적 자유는 자원의 재분배 없이는 달성되지 않으며, 자원의 재분배는 기존 권력 구조의 저항 없이는 일어나지 않는다.

**셋째, 서사적 자유(Narrative Freedom).** 이것이 가장 깊은 층이며, 가장 간과되는 층이다. 누가 “자유”를 정의하느냐의 문제다. “자유란 이것이다”라고 규정하는 자가 프레임을 장악하고, 프레임을 장악한 자가 실질적 권력을 행사한다.

링컨 시대에는 북부 산업자본이 “자유로운 노동”의 프레임을 설정했다. 자유로운 노동이란 곧 임금 노동이며, 임금 노동이야말로 문명적이라는 프레임. 이 프레임 안에서 해방된 노예가 할 수 있는 유일한 “자유로운” 선택은 공장에 취직하거나 소작 계약을 맺는 것이었다.

오늘은 빅테크가 “자유”의 프레임을 설정한다. 자유란 반복 업무로부터의 해방이며, AI 도구를 활용하는 것이야말로 진보적이라는 프레임. 이 프레임 안에서 노동자가 할 수 있는 유일한 “자유로운” 선택은 AI를 수용하고 적응하는 것이다. 거부는 퇴행이고, 저항은 러다이트(Luddite)다.

**자유의 정의를 독점하는 것. 이것이 가장 세련된 형태의 지배다.**

---

### VI. 그럼에도 불구하고: 냉소주의의 함정, 그리고 그 너머

여기까지 읽으면 자연스러운 결론은 비관이다. “자유는 착각이다. 시스템은 영원히 재생산된다. 저항은 무의미하다.” 이 결론은 지적으로 매력적이지만, 두 가지 이유에서 틀렸다.

첫째, 역사적으로 틀렸다. 노예해방이 형식적이었다는 사실이 그것을 무의미하게 만들지는 않는다. 형식적 자유가 없었다면 민권운동 자체가 법적 근거를 갖지 못했다. 인쇄기도, 인터넷도 처음엔 권력의 도구였지만, 결국 기존 구조를 해체하는 데 기여했다. 전환기의 고통과 비대칭은 실재하지만, 그것이 영구적이라는 보장은 없다.

둘째, 그리고 더 근본적으로, **인간의 투쟁만으로 자유를 설명하는 프레임 자체가 불완전하다.** 냉소주의는 “인간이 스스로 자유를 쟁취해야 하는데 그것이 불가능하다”는 전제에서 출발한다. 그런데 이 전제 자체가 틀렸다면? 자유가 애초에 인간의 힘으로 “쟁취”하는 성질의 것이 아니라면?

이 글이 지금까지 보여준 것은, 인간이 인간에게 부여하는 자유는 항상 조건부라는 사실이다. 링컨의 해방에는 북부 산업자본의 이해가 내장되어 있었다. 빅테크의 “AI 해방”에는 구독 경제와 인프라 종속이 내장되어 있다. **인간이 설계하는 자유에는 반드시 설계자의 이익이 들어간다.** 이것은 인간의 한계이지, 자유의 한계가 아니다.

---

### VII. 전환기의 경제학: 가치는 어디로 이동하는가

자유가 실체든 착각이든, 한 가지는 확실하다. **“자유”의 서사가 발생하는 곳에 항상 거대한 가치 이전(value transfer)이 일어난다.**

노예 해방 이후 미국 경제의 무게중심은 남부 농업에서 북부 산업으로 이동했다. 면화 경제는 쇠퇴했고, 철강과 철도와 석유의 경제가 부상했다. 이 전환에서 부를 축적한 것은 해방된 노예가 아니라, 전환의 인프라를 소유한 카네기, 록펠러, 밴더빌트 같은 산업 자본가들이었다.

AI 시대의 가치 이전도 같은 패턴을 따를 것이다. 전통적 노동 집약 산업에서 AI-네이티브 산업으로 가치가 대규모 이동할 것이며, 이 전환의 최대 수혜자는 “해방된” 노동자가 아니라 전환의 인프라를 소유한 자들일 것이다.

그러나 역사는 또한 보여준다. 인프라 소유자가 영원히 독점하지는 못한다는 것을. 철도 재벌은 결국 반독점법의 대상이 되었다. 록펠러의 스탠다드 오일은 해체되었다. AT&T는 분할되었다. 권력의 집중은 그에 대한 반작용을 필연적으로 낳는다. 다만, 그 반작용이 오기까지의 시간이 한 세대 이상이 걸린다는 것이 문제다.

---

### VIII. 진짜 질문

다시 처음으로 돌아가자. 자유는 사실인가, 실체인가, 아니면 개념이고 착각인가.

이 글이 추적해온 것은 **“인간이 인간에게 부여하는 자유”**의 역사다. 그리고 그 역사가 보여주는 것은 명확하다. 인간이 만든 자유는 항상 조건부이고, 항상 설계자의 비즈니스 모델이 내장되어 있으며, 항상 새로운 형태의 종속을 수반한다. 쇠사슬이 부채로, 부채가 알고리즘으로 바뀔 뿐이다.

그렇다면 무조건적 자유는 존재하지 않는 것인가.

나는 존재한다고 믿는다. 다만 그것은 인간이 인간에게 줄 수 있는 것이 아니다.

여기서 “아, 또 교회 얘기네” 하고 떠나려는 분들에게. 떠나기 전에 한 가지만 생각해보시라. 이 글이 7개 섹션에 걸쳐 증명한 것이 무엇인가. 인간이 만든 자유는 전부 사기였다는 것이다. 그런데 그 결론 앞에서 “그래도 인간이 답을 찾을 것이다”라고 말하는 것이야말로 근거 없는 믿음 아닌가.

이것은 종교적 수사가 아니다. 이 글의 논리적 귀결이다.

인간이 설계한 모든 “자유”에 조건이 붙어 있다면, 무조건적 자유는 인간의 설계 바깥에서 올 수밖에 없다. 그것을 은혜라고 부르든, 초월이라고 부르든, 명칭은 중요하지 않다. 중요한 것은 이 인식이 두 가지를 동시에 가능하게 한다는 것이다.

첫째, **세상이 파는 “자유”에 속지 않을 수 있다.** 진짜 자유를 아는 사람은 가짜 자유의 마케팅을 꿰뚫어 본다. 노예해방선언의 이면도, “AI가 당신을 해방시킨다”는 서사의 이면도. 진리가 자유롭게 한다는 것은, 진리가 거짓된 자유의 서사로부터도 자유롭게 한다는 뜻이다.

둘째, **그 자유를 받은 자에게는 책임(stewardship)이 있다.** 은혜로 자유를 받았다면, 그 자유는 나만을 위한 것이 아니다. 전환기의 소작농이 되어가는 사람들, AI 시대에 뒤처지는 사람들, 새로운 형태의 종속에 빠져드는 사람들을 위해 그 자유를 사용해야 할 의무가 있다.

투자자로서 20년간 기술과 자본의 교차점을 관찰하며 내가 배운 것은, 시장은 결국 가치가 있는 곳으로 흐른다는 것이다. 그러나 시장이 정의하는 “가치”와 인간에게 진정으로 가치 있는 것 사이에는 항상 간극이 있다. 그 간극을 인식하는 것, 그리고 그 간극 속에서 행동하는 것. 이것이 은혜를 받은 자의 투자 철학이어야 한다고 나는 믿는다.

**쇠사슬이 끊어졌다고 자유로운 것이 아니다. 쇠사슬이 있던 자리에 무엇을 놓느냐가 자유를 결정한다. 1865년에는 부채가 놓였다. 2025년에는 알고리즘이 놓이고 있다. 그러나 그 자리에 놓여야 할 것은, 처음부터 다른 무엇이었는지도 모른다.**

---

*Ethan Cho는 TheVentures의 CIO로, 기술과 자본이 만드는 권력 구조의 교차점을 20년간 관찰해왔다. 이 글은 투자 조언이 아니라, 자유라는 개념에 대한 하나의 사고 실험이다.*`,
  },

  {
    title: "What Lucent Block Actually Revealed",
    titleKo: "루센트블록이 진짜 보여준 것",
    excerpt: "[](https://substackcdn.com/image/fetch/$s!ROOX!,fauto,qauto:good,flprogressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0226e4c9-d889-4893-936b-a3cece8ff03c1086x1556.png)",
    date: "Feb 13, 2026",
    category: "Market Analysis",
    readTime: "4 min",
    canonicalUrl: "https://ethancho12.substack.com/p/a6b",
    slug: "what-lucent-block-actually-revealed",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "lucent", "actually", "revealed", "block"],
    wordCount: 748,
    rating: 3,
    content: `[![](https://substackcdn.com/image/fetch/$s_!ROOX!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0226e4c9-d889-4893-936b-a3cece8ff03c_1086x1556.png)](https://substackcdn.com/image/fetch/$s_!ROOX!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F0226e4c9-d889-4893-936b-a3cece8ff03c_1086x1556.png)

2월 13일, 금융위원회가 조각투자 장외거래소 예비인가를 최종 의결했다. NXT컨소시엄(넥스트레이드+뮤직카우)과 KDX(한국거래소+코스콤)가 선정되었고, 7년간 부동산 조각투자 시장을 개척해 온 루센트블록은 탈락했다.

한국 스타트업 생태계가 들끓고 있다. 여론의 대다수는 루센트블록을 동정한다. “시장을 만든 자가 제도화 단계에서 쫓겨났다”는 내러티브가 지배적이다. 이재명 대통령까지 국무회의에서 직접 언급했고, 금융위는 두 차례 의결을 연기한 끝에 19페이지짜리 해명자료를 배포하며 결론을 내렸다.

그러나 스타트업 투자를 해 온 입장에서, 이 사안은 “측은한 스타트업”이라는 프레임보다 훨씬 복잡하다. 양쪽 논리를 제대로 들어보면, 한국에서 규제 산업에 투자할 때 반드시 알아야 할 구조적 교훈이 드러난다.

더 다양하고 많은 컨텐츠를 구독자분들께 공유드릴 수 있도록 무료 구독 부탁드립니다 :)

**루센트블록이 맞는 부분**

루센트블록의 주장 중 가장 설득력 있는 것은 기술탈취 의혹이다. 넥스트레이드가 투자 및 컨소시엄 참여를 검토한다며 NDA를 체결하고 재무정보, 사업계획, 핵심 기술 자료를 받아간 뒤 2~3주 만에 동일 영역에서 직접 인가를 신청했다는 것이다. 이것이 사실이라면 심각한 문제다. 금융위도 이 점은 인식하고 있어서 NXT에 “공정위 행정조사 개시 시 본인가 중단”이라는 조건을 붙였다.

그리고 더 본질적으로, 샌드박스의 구조적 모순이 있다. “실험은 스타트업이 하고, 인프라 요건이 붙는 제도화 단계에서는 대형 기관이 가져간다”는 패턴은 루센트블록만의 문제가 아니다. 한국 금융 규제 산업에서 반복되어 온 구조다.

**루센트블록이 놓친 부분**

그러나 냉정하게 보면, 루센트블록의 내러티브에는 심각한 구멍이 있다.

[![](https://substackcdn.com/image/fetch/$s_!ltRo!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F8ca62727-66c0-43e2-b539-681a6accfb93_982x282.png)](https://substackcdn.com/image/fetch/$s_!ltRo!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F8ca62727-66c0-43e2-b539-681a6accfb93_982x282.png)

첫째, “혁신기업 vs 기득권”이라는 프레임이 사실과 다르다. NXT 컨소시엄에는 뮤직카우, 세종디엑스, 스탁키퍼, 투게더아트 등 4개 조각투자 스타트업이 참여하고 있다. KDX에도 카사, 펀블 등 핀테크사가 다수 합류했다. 반면 루센트블록 컨소시엄에는 조각투자 기업 중 루센트블록만 있다. 혁신기업들이 루센트블록을 선택하지 않았다는 사실 자체가 신호다.

둘째, 숫자로 보면 뮤직카우가 압도적이다. 국내 조각투자 종목의 98%, 거래대금의 73%를 차지하며 누적 거래액 4,000억 원 이상을 달성했다. 루센트블록의 2024년 유통채널 거래금액은 33억 원이다. “시장을 개척했다”는 것과 “시장을 지배하고 있다”는 것은 다른 이야기다.

셋째, 장외거래소는 “발행”이 아니라 “유통 인프라”다. 루센트블록이 잘한 것은 부동산 기초자산을 발굴하고 조각투자 상품을 발행하는 일이다. 장외거래소에 필요한 역량 — 안정적 주문처리, 거래체결, 결제연동, 불공정거래 감시 — 은 완전히 다른 영역이다. 외부평가위원회가 사업계획에서 루센트블록에 300점 만점 중 127점을 준 것은 이 차이를 반영한 것이다.

넷째, 샌드박스는 인가 보장이 아니다. 이것은 업계에서도 명확하게 지적된 바 있다. 규제 샌드박스는 실험 기회를 제공하는 장치이지, 영구적 시장 지분을 보장하는 제도가 아니다.

**VC가 이 사안에서 읽어야 할 것**

이 논란에서 진짜 교훈은 루센트블록의 억울함이 아니다. 한국에서 규제 산업에 투자할 때의 구조적 리스크를 보여준다는 점이다.

나는 이것을 ”Sandbox Trap”이라고 부른다. 한국의 규제 산업에서 스타트업이 빠지는 함정이다. 패턴은 이렇다.

1단계: 스타트업이 샌드박스로 시장을 개척한다.   
2단계: 시장이 검증되면 정부가 제도화에 나선다.   
3단계: 제도화 과정에서 인프라 요건(자본금, 인력, 지배구조)이 대형 기관에 유리하게 설정된다.   
4단계: 대형 기관이 컨소시엄을 구성해 시장을 가져간다.   
5단계: 스타트업은 “발행” 쪽 스몰라이센스를 받아 하위 밸류체인으로 밀려난다.

이 패턴이 반복되는 이유는 간단하다. 한국 금융당국의 논리 — 유동성 집중, 투자자 보호, 시장 안정성 — 가 틀린 것이 아니기 때문이다. 장외거래소가 난립하면 거래가 분산되고 가격 왜곡이 발생한다는 것은 맞는 말이다. 문제는 이 논리가 항상 기존 인프라를 가진 쪽에 유리하게 작동한다는 것이다.

**그렇다면 어떻게 투자해야 하는가**

첫째, 한국에서 규제 인허가가 핵심인 사업에 투자할 때는 “제도화 리스크”를 반드시 가격에 반영해야 한다. 샌드박스 지정이 성공의 시작이 아니라 리스크의 시작일 수 있다.

둘째, 규제 산업의 스타트업은 단독 생존이 아니라 “인프라 파트너와의 동맹”을 초기부터 설계해야 한다. 뮤직카우가 넥스트레이드와 손잡은 것은 “배신”이 아니라 합리적 생존 전략이다. 루센트블록도 금융위가 여러 차례 대형 거래소와의 컨소시엄 구성을 권했으나 반영하지 않은 것으로 전해진다.

셋째, 발행(콘텐츠)과 유통(인프라)의 분리는 불가피하다. 넷플릭스가 콘텐츠도 만들고 플랫폼도 운영하지만, 그것은 넷플릭스이기 때문에 가능하다. 자기자본 60억, 전산인력 8명을 갖추지 못하는 스타트업이라면 발행 쪽에서 경쟁력을 극대화하는 것이 현실적 전략이다.

**마지막으로**

루센트블록의 기술탈취 의혹은 별개의 문제로서 공정위가 제대로 판단해야 한다. 만약 NDA를 체결하고 정보를 가져간 뒤 경쟁자로 돌변한 것이 사실이라면, 그것은 한국 금융 산업의 관행 자체를 바꿔야 할 문제다.

그러나 “개척자가 억울하다”는 감정과 “장외거래소 인가 요건을 누가 충족하는가”는 별개의 질문이다. VC로서 우리가 해야 할 일은 감정이 아니라 구조를 읽는 것이다.

한국에서 규제 산업의 Sandbox Trap을 피하려면, 창업 첫 날부터 제도화 이후의 게임을 설계해야 한다. 시장을 만드는 것과 시장을 소유하는 것은 다른 게임이다.`,
  },

];
