// Generated by pilot/scripts/substack_to_articles_ts.py
// Source: https://ethancho12.substack.com/feed
// Generated: 2026-04-13T09:01:43
// New articles: 1 (not yet present in articles.ts)
//
// HOW TO USE:
// 1. Review each object below — titles, slugs, categories, excerpts
// 2. For Korean posts, swap the [Korean] title prefix for a real
//    English title (so cards display well in the /insights grid)
// 3. Copy the entire array contents into the `articles: Article[]`
//    declaration in app/data/articles.ts (append to the end)
// 4. Run `npm run build` to verify no TS errors
// 5. Spot-check /insights and /insights/<slug> in dev
//

import { Article } from '@/app/data/articles';

export const newArticlesFromSubstack: Article[] = [
  {
    title: "The Two Most Frightened People at Hormuz Are Not in Tehran",
    titleKo: "호르무즈에서 가장 겁에 질린 두 사람은 테헤란에 없다",
    excerpt: "호르무즈 봉쇄 뉴스에서 지금 가장 겁에 질려 있는 사람은 이란 지도부가 아니다.   \n사실 중동에 있지도 않다.",
    date: "Apr 12, 2026",
    category: "Predictions",
    readTime: "3 min",
    substackUrl: "https://ethancho12.substack.com/p/5de",
    slug: "hormuz-frightened-not-in-tehran",
    keywords: ["Ethan Cho", "TheVentures", "ventureoracle", "hormuz", "tehran", "people", "frightened"],
    wordCount: 666,
    rating: 3,
    content: `호르무즈 봉쇄 뉴스에서 지금 가장 겁에 질려 있는 사람은 이란 지도부가 아니다.   
사실 중동에 있지도 않다.

[![](https://substackcdn.com/image/fetch/$s_!iPNE!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F656786c6-2b97-4007-909a-1fa654559290_251x201.jpeg)](https://substackcdn.com/image/fetch/$s_!iPNE!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F656786c6-2b97-4007-909a-1fa654559290_251x201.jpeg)

도쿄와 샌프란시스코에 있다.   
손정의와 샘 올트먼이다.

트럼프는 일요일 소셜미디어에 미 해군이 호르무즈 해협을 즉시 봉쇄한다고 썼다. 이란이 통행료를 받는 행위를 “세계 공갈”이라 부르고, 통행료를 낸 제3국 선박까지 국제수역에서 나포하겠다고 했다. 협상 결렬에서 해상 봉쇄까지 48시간이 걸렸다.

언론은 유가와 이란과 트럼프를 본다. 그러나 이 장면에서 가장 크게 흔들리는 사람은 따로 있다.

**Stargate는 걸프 자본 없이 성립하지 않는다**

Stargate 5,000억 달러. OpenAI 인프라 라운드. 소프트뱅크 AI capex 확장. 이 세 개의 자금 조달 구조를 열어 보면 같은 이름들이 반복된다. UAE의 MGX, 사우디 PIF, Prosperity7. 걸프 국부펀드가 글로벌 AI 인프라의 자본을 댄다.

[![](https://substackcdn.com/image/fetch/$s_!Mk2r!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb98acbb4-321a-409f-9580-bf1359cad977_1400x933.jpeg)](https://substackcdn.com/image/fetch/$s_!Mk2r!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fb98acbb4-321a-409f-9580-bf1359cad977_1400x933.jpeg)

이유는 단순하다. 미국 연기금은 LP위원회 규정상 이 규모의 단일 기술 섹터 집중 투자를 감당 못 한다. 유럽 자본은 규제와 보수성 때문에 후순위다. 중국 자본은 차단됐다. 남은 건 걸프다.

손정의와 올트먼이 그리는 향후 3년 로드맵은 걸프 자본이 예정된 시점에 예정된 금액으로 들어온다는 것을 전제로 짜여 있다.

**봉쇄가 만드는 건 유가가 아니라 의사결정 지연이다**

걸프 국부펀드는 지정학 리스크에 가장 민감한 자본이다. 자국 앞바다에서 미 해군 봉쇄 작전이 벌어지는 순간, LP위원회의 의사결정 속도는 즉시 느려진다. 90일짜리 실사가 270일로 늘어난다. 분기 안에 들어오기로 한 자금이 내년으로 밀린다.

AI 인프라 capex는 분기 단위로 움직인다. GPU 선주문, 데이터센터 부지 확보, 전력 계약은 모두 on-time 자본 유입을 전제한다. LP 타임라인이 연 단위로 밀리면 전체 스케줄이 무너진다.

[![](https://substackcdn.com/image/fetch/$s_!khpF!,w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F9d63fe07-c3fe-4eb8-ba8f-1ea747bbb54f_748x622.png)](https://substackcdn.com/image/fetch/$s_!khpF!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F9d63fe07-c3fe-4eb8-ba8f-1ea747bbb54f_748x622.png)

손정의의 자금 조달은 레버리지 구조다. 담보가치 하락과 자본 유입 지연이 동시에 오면 마진콜 가능성이 열린다. 올트먼의 compute 약속은 고객과 투자자 양쪽에 걸려 있다. 약속한 연산량을 약속한 시점에 공급하지 못하면 OpenAI의 기업가치 서사 자체가 흔들린다.

둘은 운명공동체다. 한쪽이 멈추면 다른 쪽도 멈춘다.   
그리고 둘을 동시에 떠받치는 단일 자본 풀이 걸프다.

**트럼프가 blow to hell 하는 건 이란이 아닐 수 있다**

아이러니가 여기 있다. 트럼프는 미국 AI 패권을 국가 안보 의제 최상단에 올려놓은 대통령이다. 동시에 그 패권의 자금 조달 구조를 본인 손으로 흔들고 있다.

이란을 blow to hell 하겠다고 했다. 실제로 먼저 blown 되는 건 Stargate 타임라인일 수 있다.

워싱턴의 의사결정자들이 이 연결을 이해하고 있는지는 분명하지 않다. 봉쇄는 중동 정책이고, AI 인프라는 산업 정책이다. 둘을 연결하는 자본 라인은 공개 브리핑 자료에 나오지 않는다.

**한국의 위치**

걸프 자본이 risk-off로 돌아서는 구간에서, 걸프가 아닌 non-중국 AI 자본에 대한 수요는 오히려 커진다. 한국 반도체, 한국 AI 인프라, 한국 창업자가 들어갈 기회가 생긴다.

HBM 수요 곡선은 AI capex 스케줄에 직접 연동된다. Stargate가 밀리면 HBM 수요도 일시적으로 밀린다. 그러나 중기적으로는 다르다.

TSMC 집중 리스크가 재평가되고, 걸프 집중 리스크가 재평가되는 국면에서, 한국 반도체의 전략적 가치는 올라간다. 한국은 지금 mispriced 상태다. 재평가의 트리거가 어디서 올지는 아무도 몰랐다. 호르무즈가 그 트리거가 될 수 있다.

한국 창업자에게도 같은 논리가 적용된다. 미국 자본과 아시아 창업자를 동시에 읽을 수 있는 Founder Intelligence는 이런 재편 국면에서 가장 크게 재평가된다.

**정리**

호르무즈 봉쇄는 중동 뉴스로 분류되고 있다. 그러나 이 사건의 충격파가 가장 크게 도달하는 곳은 도쿄와 샌프란시스코와 아부다비의 회의실이다.

손정의와 올트먼은 자신들의 다음 3년이 걸프 자본의 on-time 유입에 달려 있다는 것을 누구보다 잘 안다. 그래서 지금 가장 겁에 질려 있는 두 사람이다.

그리고 트럼프의 봉쇄가 길어질수록, 한국 반도체의 기회가 엿보이기 시작한다.`,
  },

];
